### ISSUE TITLE
Behavior of Array() on non-array field

### ISSUE THREAD

**Issue by wI2L** [tidwall/gjson#10]
Hi

I have a particular case where a field can be either an array of strings, or a string.
Naively I tried to use `Array()` on the result when the field is a simple string to see if it would return an array with a single element, but instead the returned array is empty.

So I tried another solution, using the `myfield.#` notation on a non-array field, and I expected it to be zero, but instead i get `null`.

Do you know how I should address this use-case ? Would it be possible to return an array with a single element when using `Array()` on a non-array field ?

William

**Comment by tidwall** [comment]
I recommend that you check the `result.Type` after the `Get()` call. An array or object will return the Type `JSON` and a string will return `String`.

For example:

```go
json := `{ "item": ["abc"] }`
res := gjson.Get(json, "item")
var arr []string 
if res.Type == gjson.JSON {
        arr = res.Array()
} else {
        arr = []string{res.String()}
}
```

**Comment by wI2L** [comment]
@tidwall `result.Array()` will return an array of `gjson.Result`, so the following assignment `arr = res.Array()` is invalid.
But yeah I see the idea. Will convert the result of `Array()` to an array of string.
Tho, the whole process _could be_ included in the library so it's transparent. I don't think it add any overhead. What do you think ?

**Comment by tidwall** [comment]
Ah yes. It should look more like:

```go
json := `{ "item": ["abc"] }`
res := gjson.Get(json, "item")
var arr []gjson.Result
if res.Type == gjson.JSON {
        arr = res.Array()
} else {
        arr = []string{res}
}
```

I like the idea of having `Array()` transparently create a single item array for non-array item. I agree that it would cause little overhead, if any.

**Comment by wI2L** [comment]
@tidwall Yup that's what I ended up with because I have to convert the strings to a [x]byte type anyway.
I'll look in the source and i'll try to make a PR for this asap.
