### ISSUE TITLE
Why does memory occupy more and more

### ISSUE THREAD

**Issue by DukeAnn** [tidwall/gjson#102]
Function location ： github.com/tidwall/gjson.fromBytesGet

![image](https://user-images.githubusercontent.com/15902491/49209412-657c9280-f3f5-11e8-8116-f19965eb67a0.png)

7 minutes later

![image](https://user-images.githubusercontent.com/15902491/49209452-7cbb8000-f3f5-11e8-82b8-56e69d66c372.png)

Automatic restart until the physical machine is full of memory

code

```golang
for {
	data, err := client.Get(url)
	if err != nil {
		log.DetailError(err)
	}
	RefreshL2Cache(data)
	time.Sleep(interval * time.Second)
}
```

```golang
func RefreshL2Cache(data []byte) {
	e.l2lock.Lock()
	e.l2cache = gjson.GetBytes(data, "data.list")
	e.l2lock.Unlock()
}

```

**Comment by ivanjaros** [comment]
most likely because gjson/sjson internally work with strings, not bytes. And strings are the only immutable type in go, so each transformation/manuapilation/change of json data means new string which means it needs a memory to place the new string into.

**Comment by DukeAnn** [comment]
> most likely because gjson/sjson internally work with strings, not bytes. And strings are the only immutable type in go, so each transformation/manuapilation/change of json data means new string which means it needs a memory to place the new string into.

Yes，Memory cannot be recovered.

![image](https://user-images.githubusercontent.com/15902491/49505830-893d4e00-f8b7-11e8-9bfa-5e287f1f27c6.png)

**Comment by tidwall** [comment]
Hi DukeAnn,

I'm not able to reproduce this problem. This is what I came up with as an attempt:

```go
package main

import (
	"log"
	"sync"
	"time"

	"github.com/tidwall/gjson"
)

func main() {
	var mu sync.Mutex
	var res gjson.Result
	var data = []byte(`{"data":{"list":[1,2,3,4]}}`)
	// run a go routine with a continuous loop to ensure that
	// res escapes the heap.
	go func() {
		for {
			mu.Lock()
			log.Printf("%s", res)
			mu.Unlock()
			time.Sleep(time.Second)
		}
	}()
	// continually call gjson.GetBytes to update the res as often as possible.
	for {
		mu.Lock()
		res = gjson.GetBytes(data, "data.list")
		mu.Unlock()
	}
}
```

I ran for 5 minutes and memory usage never went above 6 MB.  

Do you have other ideas on how I can reproduce?

**Comment by DukeAnn** [comment]
It seems that JSON strings in Go take too much memory to be converted into structures, and there are 22,000 `gjson.Result{}` structures in my map [].

**Comment by tidwall** [comment]
I’m sorry but I’m unclear what the problem is. It appears that the gjson result is being stored in the l1cache map, which is why it’s staying in memory.

**Comment by DukeAnn** [comment]
`hostname = item.Get("name").String()`

 Using this method in the for loop will not be released

## Will be released

![image](https://user-images.githubusercontent.com/15902491/49844494-38b97980-fdfe-11e8-843b-fb7e98e8a1e6.png)

## Will not be released

![image](https://user-images.githubusercontent.com/15902491/49844519-54248480-fdfe-11e8-930b-4bcac618ca6d.png)


## Isn't string passing all copies? Why not be released

**Comment by tidwall** [comment]
I believe this is normal behavior. 

In your second example, `hostname` is retained in memory because `e.l1cache` is using in the line:

```go
e.l1cache[hostname] = SData
``` 

If you really really don't want the string from `gjson` to stay in memory then you can copy with something like:

```
hostname = string(append([]byte(nil), item.Get("name").String()...))
```

**Comment by DukeAnn** [comment]
Thank you,This problem has been solved, but why can't direct string copying free memory? Isn't the string in GoLang all copied?

Buffer can also be used

```
hostname := strings.Builder{}
hostname.WriteString(item.Get("name").String())
```

Can string assignment not free memory because `unsafe. Pointers` is used?

```
result.Raw = string(*(*[]byte)(unsafe.Pointer(&rawh)))
```

**Comment by ivanjaros** [comment]
isnt the issue the fact that you have two maps(caches) and you are not deleting form theme anywhere in code, just adding?

**Comment by DukeAnn** [comment]
> isnt the issue the fact that you have two maps(caches) and you are not deleting from theme anywhere in code, just adding?

I update `cache 2` regularly. The data in `cache 1` is obtained from `cache 2`. But when I assign `cache 1` map, I assign `cache 2` to `string` first, and then assign `string` to `cache 1 map`. Why hasn't memory been released yet?

**Comment by tidwall** [comment]
I do not think this is related to gjson. Perhaps the folks on gophers.slack.com could help answer questions about Go memory management.

**Comment by DukeAnn** [comment]
我找到问题了，因为使用了 string s1[10:30] 截取字符串，即使是 string 类型赋值的也不会释放底层字符串

> I found a problem because I used string S1 [10:30] to intercept strings, and even string type F assignment would not release the underlying strings.

```go

package main

const SData = "道可道，非常道；名可名，非常名。无名，天地之始，有名，万物之母。故常无欲，以观其妙，常有欲，以观其徼。此两者，同出而异名，同谓之，玄之又玄，众妙之门。"

var map1 map[int]string

func main() {
	map1 = make(map[int]string)
	var b1 []byte
	var s1 string
	var s2 string
	i := 0
	for {
		b1 = []byte(SData)
		s1 = string(b1)
		s2 = s1[10:30]
		map1[i] = s2
		i++
	}
}
```

**Comment by DukeAnn** [comment]
https://studygolang.com/articles/16921

**Comment by r--w** [comment]
At @coinpaprika, we experienced a similar problem with a memory leak inside our codebase using the gjson. Starting from Go 1.20 you can use `strings.Clone(s)`, which, in our case, solved the problem.

**Comment by cgrinds** [comment]
@tidwall would you be open to a PR that adds a new method to Result that does the cloning for folks that need to make sure the entire JSON string is eligible for GC? Something like the following which is an inlining of Go 1.20's strings.Clone() since GJSON is still on `go 1.12`.

```go
// ClonedString returns a fresh copy of t.String().
// It guarantees to make a copy of s into a new allocation,
// which can be important when retaining only a small substring
// of a much larger string. Using ClonedString can help such programs
// use less memory. Using ClonedString makes a copy, which means
// overuse of ClonedString can make programs use more memory.
// ClonedString should typically be used only rarely, and only when
// profiling indicates that it is necessary.
func (t Result) ClonedString() string {
	s := t.String()
	if len(s) == 0 {
		return ""
	}
	b := make([]byte, len(s))
	copy(b, s)
	return unsafe.String(&b[0], len(b))
}
```

**Comment by abcdsxg** [comment]
@r--w @DukeAnn  Are you using an AMD-architecture CPU? I suspect this is related. I'm using the same code for high-concurrency JSON decoding, and only servers with an AMD architecture experience memory leaks.

I've switched back to the standard JSON parser, and everything's working fine now.

Showing top 10 nodes out of 42
      flat  flat%   sum%        cum   cum%
  806.18MB 63.07% 63.07%   806.18MB 63.07%  github.com/tidwall/gjson.getBytes
