### ISSUE TITLE
Exists() condition seems erroneous

### ISSUE THREAD

**Issue by abourget** [tidwall/gjson#104]
The code for `Exists` is: 

```
func (t Result) Exists() bool {
	return t.Type != Null || len(t.Raw) != 0
}
```

But it seems to me this should read: 

```
func (t Result) Exists() bool {
	return t.Type != Null && len(t.Raw) != 0
}
```

why specify `Type != Null` if the second clause overrules it always?

With a `null` value here, you get `Exists()` == true.

**Comment by tidwall** [comment]
Calling `Exists` on an explicit null value should return true.
With your change this returns false:

```
println(gjson.Get(`{"value":null}`, "value").Exists())
```

**Comment by maoueh** [comment]
What is the correct semantics of ˋExists`? Key exists (whatever it’s value)? Or value being non-null?

**Comment by tidwall** [comment]
@maoueh  `Exists` returns true when a key exists, whatever it's value. `Exists` returns false when the key does not exist in the json.

**Comment by abourget** [comment]
Then you'd only need `len(t.Raw) != 0` right?

**Comment by abourget** [comment]
And the issue that I got at first is that when doing a `ForEach` iteration of a `null` value, `ForEach` will enter the function with an empty element. `ForEach` checks for `Exists()` and returns if it's false, but `null` counts as `true`, so it goes through an iterate on the element.. even if it's not an Array or an Object.

**Comment by tidwall** [comment]
> Then you'd only need len(t.Raw) != 0 right? 

There are some operations that set the `t.Type` to something other than `Null` and at the same time the `t.Raw` is empty. Such as:

```go
gjson.Get(`{"friends":["tom","jane"]}`, "friends.#")
```

**Comment by abourget** [comment]
okay, and I see the docs cover the `ForEach` behavior as you explained it.

thanks for your patience :) thanks for the lib !

**Comment by tidwall** [comment]
You're welcome and thanks for using the library. :)
