### ISSUE TITLE
Decoding bytes in GopherJS

### ISSUE THREAD

**Issue by kyeett** [tidwall/gjson#106]
Hi,

I'm using a package that in turn uses gjson to read json. I run into problems when I try to compile to JS to run it in browser. I have stored my assets as byte-arrays, so they can be compiled into go.

This works well locally, but not in the browser. I'm loading Character_json, 

```
fileBytes := resources.Character_json
fmt.Println(gjson.ValidBytes(fileBytes)) // OK!
gjson.GetBytes(fileBytes, "frames")
```
https://github.com/kyeett/platformer/blob/master/assets/graphics.go

Are there any known limitations of gjson not being supported in GopherJS? I saw that your playgroad runs on it.

/Magnus

**Comment by tidwall** [comment]
Hi Magnus, 

I've used gjson in GopherJS and I'm not aware of any problems. Though I haven't used the `*Bytes` functions. 

I'd like to diagnose the problem. Could you try the string functions instead and report back if you are seeing the same issues?

```
fileString := string(resources.Character_json)
fmt.Println(gjson.Valid(fileString)) // OK!
gjson.Get(fileString, "frames")
```

**Comment by kyeett** [comment]
That works! I though gjson.GetBytes() did basically just that :-)

**Comment by tidwall** [comment]
You're right that gjson.Get and gjson.GetBytes are basically the same thing. One is for a string input and the other is for bytes. You discovered a bug with gjson.GetBytes and GopherJS. 

Good news is that I just pushed a fix!

Thanks for reporting :)

**Comment by kyeett** [comment]
Oh, that's great :-) Thank you for your quick response. I will try the fix later today!
