### ISSUE TITLE
Purpose of ParseBytes?

### ISSUE THREAD

**Issue by ivanjaros** [tidwall/gjson#107]
Hi,
I am just curious as to why the ParseBytes() says to use it instead of typing bytes into string and calling Parse() since internally that is exactly what it does:

```
// ParseBytes parses the json and returns a result.
// If working with bytes, this method preferred over Parse(string(data))
func ParseBytes(json []byte) Result {
	return Parse(string(json))
}
```

Is this for backwards compatibility?

**Comment by tidwall** [comment]
I wanted `ParseBytes` and `GetBytes` functions that both accept the `[]byte` as the first param.
