### ISSUE TITLE
Could you add a GetMany function for Result structure?

### ISSUE THREAD

**Issue by m3ng9i** [tidwall/gjson#108]
Hi, I found there is a `Result.Get()`, but there's no `Result.GetMany()`. Could you add one?

**Comment by tidwall** [comment]
I'll consider this in a future release. 

Until then, the equivalent can be achieved by:

```
gjson.GetMany(Result.Raw, "path1", "path2")
```

**Comment by m3ng9i** [comment]
That's great. Thanks.
