### ISSUE TITLE
Interoperability issue between sjson and gjson on AppEngine

### ISSUE THREAD

**Issue by sHesl** [tidwall/gjson#110]
Hi @tidwall, huge fan of this lib! Never had any issues until I tried using it along sjson on AppEngine, where I noticed `sjson.Set*` and `sjson.Delete*` don't appear to be working as intended. Though the bug is encountered when using sjson, I believe the root cause is here inside gjson.

I believe this is because the `fillIndex` [func is noop'd for GAE](https://github.com/tidwall/gjson/blob/master/gjson_gae.go#L9), but [sjson needs to use the index](https://github.com/tidwall/sjson/blob/master/sjson.go#L262) to determine where to append/delete the field from.

The result is all `Set*` calls simply prepend the field to the start of the JSON, while all `Delete*` calls always return an `errNoChange`.

**Comment by tidwall** [comment]
Sorry I haven't responded sooner. I don't have immediate access to AppEngine resource and debugging & development is a little slow for me for that platform. I'll need to dig into this problem a little deeper, but I think the problem stems from the use of the `unsafe` package for determining byte offsets for `fillIndex`. There's probably a better way to handle this. When I find a solution I'll ping this issue. Thanks!

**Comment by sHesl** [comment]
No worries @tidwall. FYI, it turns out [unsafe is now importable in the Go 1.11 runtime](https://news.ycombinator.com/item?id=18230938) , so at least there is a workaround (which I was able to employ for my case).

**Comment by tidwall** [comment]
That's great to hear. It's been an annoyance to deal with supporting special GAE builds.

Considering GAE intends on supporting unsafe moving forward, I think I'll not make any changes until a new big release. So that we can maintain the same level of compatibility for Go 1.9 GAE users.

Perhaps soon I can remove the `_ngae.go` and `_gae.go` files altogether.
