### ISSUE TITLE
Parsing a key containing . is failing

### ISSUE THREAD

**Issue by continuum-dipanjan-mazumder** [tidwall/gjson#117]
Hi,,

   As per the example:

       "fav\.movie"         >> "Deer Hunter"

This does not work with below program:
const json = `{
  "name": {"first": "Tom", "last": "Anderson"},
  "age":37,
  "children": ["Sara","Alex","Jack"],
  "fav.movie": "Deer Hunter",
  "friends": [
    {"first": "Dale", "last": "Murphy", "age": 44},
    {"first": "Roger", "last": "Craig", "age": 68},
    {"first": "Jane", "last": "Murphy", "age": 47}
  ]
}`

package main

import (
	"fmt"

	"github.com/tidwall/gjson"
)
func main() {
	value := gjson.Get(json, "fav/.movie")
	fmt.Println(value.Raw)

}

**Comment by tidwall** [comment]
I think you are using the wrong slash. It should be `fav\.movie`
