### ISSUE TITLE
The question about the character ‘#’

### ISSUE THREAD

**Issue by wolking** [tidwall/gjson#118]
code：
```
	s := `[{"a":10.1,"b":"c","c":[{"a":10.11}]},{"a":11,"b":"d","c":[{"a":11.11}]}]`
	a := gjson.Get(s, "#.c.#.a").Array()
	fmt.Println(a[0].Float())
```
result：a[0].Float()=0
Debug:
![image](https://user-images.githubusercontent.com/12195297/58089818-4dddd400-7bf8-11e9-84e4-89fe4576c907.png)
It should be 10.11
Isn't it?

**Comment by wolking** [comment]
One character '#' means an array [...], two characters '#' means Two-dimensional array [[...],[...],...], is that right?

**Comment by tidwall** [comment]
I think you're on the right path.

The `#.c` returns

```json
[[{"a":10.11}],[{"a":11.11}]]
```

You'll need to use the `|` character to do multi-dimensional stuff

The `#.c|0.0.a` returns

```
10.11
```

----

Which basically says "Return an array containing only the 'c' members"

```
[[{"a":10.11}],[{"a":11.11}]]
```

"Then take the element at index '0', which is an array, then next array at index '0', then the value associated with 'a'"

----

I added some [new documentation](https://github.com/tidwall/gjson/blob/master/SYNTAX.md) that gives examples around how the `#` works with the `|`.

Also please make sure to update to the recent version v1.2.2. I made some pretty big changes that may affect the result.

**Comment by tidwall** [comment]
I think that this issue is resolved. But if you run into any problems or have more questions relating to this issue, please feel free to reopen.

**Comment by wolking** [comment]
Thank you very much.

**Comment by tidwall** [comment]
You’re welcome.
