### ISSUE TITLE
Exist return empty array, but must return nil

### ISSUE THREAD

**Issue by oranze** [tidwall/gjson#119]
I got a problem. So checking a lot of paths and all fine, but with one got problem.

JSON: 

`{
  "XTC_Push": {
    "InternalSeq": "15",
    "InternalTime": "2019-05-01 00:00:24",
    "sequence": "809576",
    "timestamp": "2019-05-01 00:00:22",
    "meeting": {
      "id": "161366",
      "active": "Y",
      "races": {
        "race": {
          "id": "1448045",
          "number": "1",
          "runners": {
            "runner": [
              {
                "id": "14529414",
                "startnr": "1",
                "prognr": "1",
                "starter": "Y"
              },
              {
                "id": "14529415",
                "startnr": "2",
                "prognr": "2",
                "starter": "Y"
              },
              {
                "id": "14529416",
                "startnr": "3",
                "prognr": "3",
                "starter": "Y"
              },
              {
                "id": "14529417",
                "startnr": "4",
                "prognr": "4",
                "starter": "Y"
              },
              {
                "id": "14529418",
                "startnr": "5",
                "prognr": "5",
                "starter": "N"
              },
              {
                "id": "14529419",
                "startnr": "6",
                "prognr": "6",
                "starter": "N"
              },
              {
                "id": "14529420",
                "startnr": "7",
                "prognr": "7",
                "starter": "Y"
              },
              {
                "id": "14529421",
                "startnr": "8",
                "prognr": "8",
                "starter": "Y"
              }
            ]
          }
        }
      }
    }
  }
}`

This is my debug output:

`809576
"809576"
    rule XTC_Push.sequence VALID
161366
"161366"
    rule XTC_Push.meeting.id VALID
Y
"Y"
    rule XTC_Push.meeting.active VALID
1448045
"1448045"
    rule XTC_Push.meeting.races.race.id VALID

{"runner": [{"id": "14529414", "startnr": "1", "prognr": "1", "starter": "Y"}, {"startnr": "2", "prognr": "2", "starter": "Y", "id": "14529415"}, {"startnr": "3", "prognr": "3", "starter": "Y", "id": "14529416"}, {"id": "14529417", "startnr": "4", "prognr": "4", "starter": "Y"}, {"prognr": "5", "starter": "N", "id": "14529418", "startnr": "5"}, {"id": "14529419", "startnr": "6", "prognr": "6", "starter": "N"}, {"starter": "Y", "id": "14529420", "startnr": "7", "prognr": "7"}, {"starter": "Y", "id": "14529421", "startnr": "8", "prognr": "8"}]}
    rule XTC_Push.meeting.races.race.runners VALID

[{"id": "14529414", "startnr": "1", "prognr": "1", "starter": "Y"}, {"startnr": "2", "prognr": "2", "starter": "Y", "id": "14529415"}, {"startnr": "3", "prognr": "3", "starter": "Y", "id": "14529416"}, {"id": "14529417", "startnr": "4", "prognr": "4", "starter": "Y"}, {"prognr": "5", "starter": "N", "id": "14529418", "startnr": "5"}, {"id": "14529419", "startnr": "6", "prognr": "6", "starter": "N"}, {"starter": "Y", "id": "14529420", "startnr": "7", "prognr": "7"}, {"starter": "Y", "id": "14529421", "startnr": "8", "prognr": "8"}]
    rule XTC_Push.meeting.races.race.runners.runner VALID

["1","2","3","4","5","6","7","8"]
    rule XTC_Push.meeting.races.race.runners.runner.#.startnr VALID

["1","2","3","4","5","6","7","8"]
    rule XTC_Push.meeting.races.race.runners.runner.#.prognr VALID

[]
    rule XTC_Push.meeting.races.race.runners.runner.#.winodd VALID`

So last one can't be valid because it's not exist, but for some reason Get method return it like a array [] with len = 1

**Comment by oranze** [comment]
The checking code looks like that:

`for _, e := range templateRulesArr {
						e = strings.TrimSpace( e )
						if  len(e) > 1 {
							if !messageObj.Get( e ).Exists(){
								templateValidType = false
									fmt.Println("    rule "+e+" NOT VALID")
								break
							} else{
								// fmt.Println(len(messageObj.Get( e ).Array()))
								fmt.Println("    rule "+e+" VALID")
							}
						}
					}`

**Comment by tidwall** [comment]
Using `#` returns a valid array containing the 0-N matching members. `Exists` is checking if the array exists, which is always does, and returning true. 

If you want an empty array to be considered not valid, then perhaps something like this:

```go
for _, e := range templateRulesArr {
    e = strings.TrimSpace( e ) 
    if len(e) > 1 { 
        res := messageObj.Get( e )
        if !res.Exists() || (res.IsArray() && res.Get("#").Int() == 0) { 
            templateValidType = false fmt.Println(" rule "+e+" NOT VALID")
            break 
        } else { 
            // fmt.Println(len(messageObj.Get( e ).Array())) 
            fmt.Println(" rule "+e+" VALID") 
        } 
    } 
}
```
