### ISSUE TITLE
Support rfc6901 syntax

### ISSUE THREAD

**Issue by aeneasr** [tidwall/gjson#121]
Expressing the path to a JSON key is being standardized by the IETF with RFC6901 ("JSON Pointer"). I wanted to check if there are any plans to support the syntax proposed by that RFC and if so, what needs to be done to support that.

**Comment by tidwall** [comment]
I haven't encountered RFC6901 before now. But from a cursory look the syntax seem similar to gison. Perhaps all that's needed is a path conversion function that converts the "JSON Pointer" slash syntax to gjson syntax. 

`#/name/first` -> `name.first`
