### ISSUE TITLE
Improvement for GetMany

### ISSUE THREAD

**Issue by WalnutATiie** [tidwall/gjson#122]
GetMany searches json for the multiple paths. Its Implementation uses For-Range to traverse multiple paths, is there any better way to improve it?

GetMany的实现是写了个for循环调用Get，在执行的过程中会扫字符串多次，这点有没有好的方式能够优化一下呢？

**Comment by tidwall** [comment]
Yes, there's a couple of possibilities for improvement in the future. At some point, I'll address. Thanks.
