### ISSUE TITLE
Cannot filter a list of primitives

### ISSUE THREAD

**Issue by djoodle** [tidwall/gjson#123]
I was hoping something like the following would be supported:

```
source := `{"list": ["apples", "avacados", "bananas", "carrots"]}`
match := `list.#[%"a*"]`
value := gjson.Get(source, match)
value == ["apples", "avacados']
```

Is there a way to do this currently? or Pointer to where i could add the functionality?

**Comment by tidwall** [comment]
Unfortunately, the gjson syntax does not allow for that functionality.
