### ISSUE TITLE
Retrieve all paths for a given object (flatten)

### ISSUE THREAD

**Issue by aeneasr** [tidwall/gjson#128]
This is a truly awesome library - thank you!

I wanted to check if there's an idiomatic way in this lib to get all the paths for an arbitrary JSON object/array. For example

```json
{ "foo": [{ "bar": "baz" }], "baz": true }
```

would return keys

```
"foo.0.bar": "baz"
"baz": true
```

Thank you!

**Comment by tidwall** [comment]
Unfortunately there's nothing like that built into the library.

**Comment by aeneasr** [comment]
Ok thanks, I wrote a simple traverse/flatting logic to address this :)
