### ISSUE TITLE
Query many paths at once

### ISSUE THREAD

**Issue by FZambia** [tidwall/gjson#13]
@tidwall hello, thanks for a nice library. 

I have a question - in my case I need to query several keys from JSON payload, all on top level. As far as I understand it's only possible to do in several calls to `Get` method. It could be much more efficient to have something like `GetMany` which accepts a list of paths and returns several Result objects making only one scan over JSON payload. Something like [EachKey](https://godoc.org/github.com/buger/jsonparser#EachKey) method from `jsonparser` lib. 

I looked into `gjson` internals and it seems to me that it's not an easy task to add such a feature. But I just decided to ask - what do you think about this?

**Comment by tidwall** [comment]
Hi @FZambia,

I totally agree that this would be a great feature. I started working on a solution a few months ago but I got side-tracked and have yet to complete it.

I think I'll start the project up again and hammer it out.
