### ISSUE TITLE
Implement binary marshaler and unmarshaler for Result object

### ISSUE THREAD

**Issue by rosspatil** [tidwall/gjson#131]
Can we implement binary marshaler and unmarshaler for Result object?
Sometimes I found some extra efforts where I manually need to convert object into []byte, however the vendor already has the provision to call binary marshaler within itself.
This is very useful when we are passing Result object to any database for storage.

**Comment by tidwall** [comment]
I designed the `Result` object to be an intermediate working type following a `Get()` operation. I feel that marshal and unmarshall methods are outside of it's intended purpose.

In Go, it's possible to create custom wrapped types that "inherit" the functionality of another type. I recommend wrapping the `gjson.Result` type which implements the necessary `MarshalBinary/UnmarshalBinary` functions.



```go
package main

import (
	"encoding/json"

	"github.com/tidwall/gjson"
)

type Result struct {
	gjson.Result
}

func (res *Result) MarshalBinary() ([]byte, error) {
	return json.Marshal(res.Result)
}
func (res *Result) UnmarshalBinary(data []byte) error {
	return json.Unmarshal(data, &res.Result)
}

func main() {
	json := `{"first": "James", "last": "Murphy"}`
	res := Result{gjson.Get(json, "first")}
	bytes, err := res.MarshalBinary()
	if err != nil {
		panic(err)
	}
	var res2 Result
	if err := res2.UnmarshalBinary(bytes); err != nil {
		panic(err)
	}
	println("equal:", res == res2)

}
```

**Comment by rosspatil** [comment]
but every time I have to use my Result object in the projects.

**Comment by tidwall** [comment]
Adding a binary format to gjson is outside the scope the core library. So the only option is to handle the custom marshaling in your project.

**Comment by tidwall** [comment]
Optionally you could fork the project and add the functionality.

**Comment by rosspatil** [comment]
> Optionally you could fork the project and add the functionality.

Yah that seems better in my case

Thanks man
