### ISSUE TITLE
Need GetIfExists methods with default

### ISSUE THREAD

**Issue by Sheridan** [tidwall/gjson#132]
Quite often it is necessary to write code similar to this
```
        result := "default"
        value := json.Get(key)
	if value.Exists() {
		result = value.String()
	}
```
Can I ask you to expand the package with method like this: `gj.GetIfExists("key", gj.newResult("default"))` ?

**Comment by tidwall** [comment]
Maybe an extension package that provides that functionality would be best. Then you could control the serialization of the default value.

```go
package gjsonex

func GetDefault(json, path, default string) gjson.Result{
	if res := gjson.Get(json,path); !res.Exists() {
		return gjson.Parse(default)
	} else {
		return res
	}	
}
```

```go
gjsonex.GetDefault(json, key, `"default"`);
```
