### ISSUE TITLE
Validate path selectors or specify a regex for them

### ISSUE THREAD

**Issue by paralin** [tidwall/gjson#135]
It would be useful to be able to validate path selectors, and/or include a regex for what a valid path selector looks like.

**Comment by tidwall** [comment]
I agree. That sounds useful.

**Comment by tidwall** [comment]
I'm closing for now, but feel free to reopen if needed.

**Comment by paralin** [comment]
What made you close

**Comment by tidwall** [comment]
The issue went stale. Were you planning a PR?

**Comment by paralin** [comment]
So it's your policy to just close any "nice to have" feature that you can't merge within a certain window?
