### ISSUE TITLE
Indexed access?

### ISSUE THREAD

**Issue by howesteve** [tidwall/gjson#136]
Hello,

This is not a bug report but a question: is the properties access indexed after I call Parse()? I mean, if I Get("widget.window.name"), will it be efficient as a map[] call or will it involve parsing/sequential scans in any way?
Still didn't look thoroughly at the source as I should. ..

Thanks,
Howe

**Comment by tidwall** [comment]
There's no indexing. `Parse` turns the input json into a `gjson.Result`. Each Get call will sequentially scan the json looking for the path.

As for which is more efficient, Get or directly accessing a map. Directly accessing a map will likely be much faster. But unmarshalling to a map or a struct can be slow. Also, gjson doesn't allocate memory in most cases.

If you just need to query json for a few fields, then gjson is very fast. Much faster than unmarshalling then accessing the field through a map or a struct. 

But if you need to unmarshal a big json payload and hang on to it for a while, for random reads and such, then unmarshalling may be the way to go.

Here's a little program I whipped up that does some comparisons.

https://gist.github.com/tidwall/fe54118e1c46875b0fa79f2e61e42b2b

**Comment by howesteve** [comment]
Ah! Many thanks. That's exactly what I wanted to know.
