### ISSUE TITLE
bug of parse string with slash

### ISSUE THREAD

**Issue by kSpacer201** [tidwall/gjson#137]
when I run
```go 
fmt.Println(
	gjson.Parse(
		`{ "a" : "c:\m\m\m.exe" }`,
	).Value(),
)
============ stdo utput ===========
map[a:c:]
```
as you see, strings after slash is disappeared. 
But I found a method to resolve this ,
```go
fmt.Println(
	gjson.Parse(
		strings.ReplaceAll(
			`{ "a" : "c:\m\m\m.exe" }`,
			`\`, `\\`,
		),
	).Value(),
)
============ std output ===========
map[a:c:\m\m\m.exe]
```

the eaten letters comes back.
will you fix this ?

**Comment by tidwall** [comment]
```
{ "a" : "c:\m\m\m.exe" }
```

That's not valid json. The only allowable escape characters are:

`\"` `\/` `\b` `\f` `\n` `\r` `\t` `\u0000`

**Comment by kSpacer201** [comment]
Ummmm , I see . I read websocket message ,  the parsed error joined in from that.

**Comment by tidwall** [comment]
If you are uncertain whether the json is valid, you can check it beforehand with `gjson.Valid(json)`.

For example:

```go
json := `{ "a" : "c:\m\m\m.exe" }`
if (gjson.Valid(json)) {
    gjson.Parse(json).Value()
}

```

**Comment by kSpacer201** [comment]
Great! This is very helpful.
