### ISSUE TITLE
foreach doesn't give you a filled in key value

### ISSUE THREAD

**Issue by Godley** [tidwall/gjson#139]
Hi there, I'm trying to get at some values that are in keys which I may or may not know the full path of. When using `forEach` I need to know the key's value but it comes back as blank every time, for example in this goplayground - https://play.golang.org/p/YEVfzdSPatX

This doesn't happen if you use `Parse(json).ForEach()` with no query. Any idea why this is happening?

**Comment by tidwall** [comment]
Hi.

The reason that it's not working is becuase, for this json

```
{"name.last":"Prichard","age":47}
```

the operation

```
gjson.Get(json, `name\.*`)
```

returns 

```
"Prichard"
```

which is equivlent to

```
gjson.Parse("Prichard").ForEach(key, value gjson.Result)
```

Thus the original key is lost on the initial `gjson.Get`

**Comment by Godley** [comment]
Right...so...if I wanted to get the key, how would I go about it?

**Comment by tidwall** [comment]
> I don't really understand why that should result in the foreach not having a filled in key.

A gjson.Get() call finds the value belonging to the path. In your case it finds "Prichard". The "name.last" key is not a part of the result. 
When you call ForEach on the result, you are effectively calling ForEach on the simple JSON string "Prichard".

> how would I go about it?

Use the ForEach around the json member that is the parent to the target children's keys.

```go
json := `{"name.last":"Prichard","age":47}`

gjson.Parse(json).ForEach(func(key, value gjson.Result) bool {
	if strings.HasPrefix(key.String(), "name.") {
		println(key.String())
		println(value.String())
	}
	return true
})

// Output:
// name.last
// Prichard
```

https://play.golang.org/p/1nkw9wzY4SR

**Comment by tidwall** [comment]
Hi @Godley, 
I'm closing this issue because it's been a few weeks without an update, but feel free to reopen if needed. Thanks :)
