### ISSUE TITLE
Select array element as a whole

### ISSUE THREAD

**Issue by chuttam** [tidwall/gjson#14]
See playground snippet here: https://play.golang.org/p/lnK6hp8ECs

From the following example JSON:

```json
[
  {
    "items": [
      {
        "id": "id-a1",
        "cost": "cost-a1",
        "rating": "terrible"
      },
      {
        "id": "id-a2",
        "cost": "cost-a2",
        "rating": "bad"
      }
    ],
    "tag": "abc"
  },
  {
    "items": [
      {
        "id": "id-b1",
        "cost": "cost-b1",
        "rating": "bad"
      },
      {
        "id": "id-b2",
        "cost": "cost-b2",
        "rating": "good"
      }
    ],
    "tag": "xyz"
  }
]
```
I'd like to select from the array a collection of `items` and the `tags` that correspond to each item set array. For example, when selecting from the collection items with `rating = good`, I would get the following ideal outcome:

```json
[
  [
    {
      "id": "id-b2",
      "cost": "cost-b2",
      "rating": "good"
    }
  ],
  [
    "xyz"
  ]
]
```

```
gjson.GetMany(jsonData, `#.items.#[rating="good"]`, `#.tag`)
```
gets me close, by just returning item `id-b2`, but still gives me both tags `xyz` and `abc` in the second array returned. Ideally that second array would give me just `xyz` .

Is this type of selection outcome even possible at the moment?

Also, I'm not sure if I've been able to explain the problem appropriately, but I thought it would be easier to explain via a (very) hypothetical JSON example that I distilled from a more complex real-world JSON setup.

**Comment by tidwall** [comment]
No this is currently not possible. GJSON does not support backtracking.

A workaround could be:

```go
for _, outer := range gjson.Parse(json).Array() {
	el := arr.Get(`items.#[rating="good"]`)
	if el.Exists() {
		println(el.String())
		println(outer.Get("tag").String())
	}
}
```
