### ISSUE TITLE
multistring selector returns empty object at the end

### ISSUE THREAD

**Issue by errashe** [tidwall/gjson#141]
```go
gjson.GetBytes(resp.Body(), "data.#.C_NAME").Array()
```
return 42 (for example) objects, but
```go
gjson.GetBytes(resp.Body(), "data.#.{C_NAME}").Array()
```
return 43 objects. And the last one is empty.

JSON looks like - 

```JSON
{
  "data": [{}, {}, {}, {} ...],
  "sql": "string with sql"
}
```

**Comment by errashe** [comment]
It's happens only with `data.#.{C_NAME}`. So, u can use:
```GO
gjson.Get(gjson.getBytes(resp.Body(), "data").String(), "#.{C_NAME}").Array()
```

And there is 42 objects (as expected).

**Comment by tidwall** [comment]
Hi, Could you please provide the json with your example, and what you expect to happen. Thanks.

**Comment by errashe** [comment]
https://gist.github.com/errashe/5a33ed53c11370c66f43845900386127

Here's example - same json, only one difference for path is `{}`. Same for multiselection.

**Comment by tidwall** [comment]
Fixed. Thanks.
