### ISSUE TITLE
How to use parameter to get nested array value

### ISSUE THREAD

**Issue by kc1awv** [tidwall/gjson#145]
In the example given
```go
name := gjson.Get(json, `programmers.#(lastName="Hunter").firstName`)
println(name.String())  // prints "Elliotte"`
```
to grab a value from a nested array, how can a parameter from a function be used? i.e. instead of "Hunter", use any lastName to return the firstName.

So far I have been unsuccessful :) I've been thinking of something like this:
```go
func getFirstName (lName string) string {
    input, err := ioutil.ReadFile(jsonFile)
    if err != nil {
        fmt.Println(err)
    }
    jsonLookup := string(input)
    fName := gjson.Get(jsonLookup, `programmers.#(lastName="lName").firstName`)
    return (fName.String())
}
```

**Comment by kc1awv** [comment]
Well, I think I've spoken too soon. Looks like it's all about proper formatting :)
```go
fName := gjson.Get(jsonLookup, `programmers.#(lastName=`+lName+`).firstName`)
```
Looks like this gives me the result I am looking for. Not sure if there's a more efficient way.

**Comment by tidwall** [comment]
👍  Glad you found a solution.
