### ISSUE TITLE
support alternate base json module

### ISSUE THREAD

**Issue by rjammala** [tidwall/gjson#146]
Hi

This is more a request than an issue. Was wondering if gjson (and also sjson and pretty) can support another base json module like https://github.com/segmentio/encoding

**Comment by tidwall** [comment]
Hi, 

The segmenio/encoding/json library looks to be a replacement to the built-in encoding/json, which rely on the Go marshal/unmarshal patterns. Gjson and sjson take on different approaches to working with json. 

I'm not seeing how gjson could benefit from supporting the other library.

**Comment by rjammala** [comment]
I have noticed at least one place where encoding/json is used in gjson:
https://github.com/tidwall/gjson/blob/master/gjson.go#L1818

I was hoping for a performance bump by using the segmentio version.

Feel free to close this issue if you don't see any benefit of this change. Thanks.

**Comment by tidwall** [comment]
The use of the stdlib json package is a fallback for a not-so-often code path. I don’t expect changing the dependency will effect much performance.
