### ISSUE TITLE
Path syntax for a string

### ISSUE THREAD

**Issue by timp87** [tidwall/gjson#148]
Hello.

Let's assume I have the following JSON:
```
"192.168.1.1:25"
```
This is a plain string which is a valid JSON

What path should I use for gjson.Get() to get exactly the same string as result?

**Comment by tidwall** [comment]
gjson.Get() works on JSON objects and arrays. You can use gjson.Parse() to convert any JSON type into a gjson.Result.

```
json := "192.168.1.1:25"
res := gjson.Parse(json)
println(res.String(), json)

// output:  "192.168.1.1:25"  "192.168.1.1:25"
```

**Comment by tidwall** [comment]
There's a new way to get the root element using the `@this` modifier. 

```
gjson.Get(`"192.168.1.1:25"`, "@this") >> `"192.168.1.1:25"`
```

I'm closing this issue for now, but feel free to reopen if needed.
