### ISSUE TITLE
Select all matches in array

### ISSUE THREAD

**Issue by chuttam** [tidwall/gjson#15]
Go playground: https://play.golang.org/p/hDZZPbCwXD

For this JSON:

```json
{
  "friends": [
    {
      "first": "James",
      "last": "Murphy"
    },
    {
      "first": "Roger",
      "last": "Craig"
    },
    {
      "first": "James",
      "last": "The Second"
    }
  ]
}
```

```
allJames := gjson.Get(jsonData, `friends.#[first="James"]`)
```

gives me just `{"first": "James", "last": "Murphy"}`

How would one select both "James" friends?

**Comment by tidwall** [comment]
The `#[]` structure only takes the first match. There's currently no way to get all matches with a single `Get` call. But it's possible to do:

```go
for _, el := range gjson.Get(json, `friends`).Array() {
	if el.Get("first").String() == "James" {
		println(el.String())
	}
}
```

It may not be ideal, but should perform pretty well.

**Comment by tidwall** [comment]
I just pushed an update with allows for multiple results to be returned by using this syntax:

```
allJames := gjson.Get(jsonData, `friends.#[first="James"]#`)
```

**Comment by chuttam** [comment]
Top stuff. Was going to PR it too, but your solution is much better (naturally). Cheers. 🎩

**Comment by tidwall** [comment]
Thanks for the kind words. :)
