### ISSUE TITLE
query key == value

### ISSUE THREAD

**Issue by universam1** [tidwall/gjson#151]
Great work here!

I really like the query syntax as it allows moving the logic into definitions!
Given:
```json
{
  "sub":"xyz",
  "children": ["Sara","Alex","Jack"]
}
```
I can nicely test a match of an array:
`children.#(%"Alex") `

However, if I like to test a match for an object I would expect this to work
`sub=="xyz"` which doesn't.

I really cannot add code / condition checking in my function because it would make this library obsolete
Thank you for suggestion!

**Comment by tidwall** [comment]
Querying elements and performing comparison operations only work on arrays. 

One option is to use the brand new `@this` modifier, and wrap the document in an array. Then do the query.

```
[@this].#(sub=="xyz")
```

**Comment by universam1** [comment]
That is very helpful - and it works perfectly fine!

Thank you very much for prompt support - guess this example would be great to add to docs?

**Comment by tidwall** [comment]
You're welcome. I too just noticed that it's not anywhere in the docs. I just added it to the gjson.dev site and I'll add it to the other docs too. Thanks!

**Comment by universam1** [comment]
@tidwall just in case to ask the obsolete, would it be possible to add shortcut to this notation in a way that would reduce cognitive challenge?

Asking because we like to use this library as a generic query syntax for json structure, and comparision operations are the common use case.

Would it be for example possible to internaly wrap a syntax like 
```
x<operator>"y"
```
into this valid syntax?
```
[@this].#(x<operator>"y")
```
Thank you for consideration!

**Comment by universam1** [comment]
@tidwall Or if above is not possible - do you have a suggestion how a wrapper could be expressed?

**Comment by tidwall** [comment]
You could add a custom modifier. In the example below I added one called `@query` that accepts a `x<operator>"y"` style query as an argument.

```
gjson.AddModifier("query", func(json, arg string) string {
	return gjson.Get(json, "[@this].#("+arg+")").Raw
})

println(gjson.Get(json, `@query:sub=="xyz"`).Raw)
```

**Comment by universam1** [comment]
Thank you for that suggestion!
