### ISSUE TITLE
The Get function does not parse key that contain dot(.)

### ISSUE THREAD

**Issue by Prithvipal** [tidwall/gjson#154]
I want to use gjson in my project to parse JSON. I have a JSON string that has some keys that contain a dot(.) but it doesn't parse a key that contains do(.)

Following is the example code:

```
package main
import (
	"fmt"

	"github.com/tidwall/gjson"
)

func main() {
	json := `
	{
		"key1.1.0": "value1"
	}
	`
	val := gjson.Get(json, "key1.1.0")
	fmt.Println(val)
}

```

**Comment by tidwall** [comment]
You need to [escape](https://github.com/tidwall/gjson/blob/master/SYNTAX.md#escape-character) the dot character:

```
val := gjson.Get(json, "key1\.1\.0")
```

**Comment by Prithvipal** [comment]
Thanks for the reply @tidwall 

This does not work. It gives a compilation error: **unknown escape sequence**
The following statement solved my problem:

`val := gjson.Get(json, "key1\\.1\\.0")`

I think we should update the documentation as well.

**Comment by tidwall** [comment]
I edited my comment above to include the `\\` slash. Alternatively, you can do:

```
val := gjson.Get(json, `key1\.1\.0`)
```

**Comment by Prithvipal** [comment]
I have raised PR for the documentation fix:
https://github.com/tidwall/gjson/pull/155

**Comment by Prithvipal** [comment]
The solution in your latest comment also worked. Thank you for your help.
Closing the issue.
