### ISSUE TITLE
ForEach() and "Result"

### ISSUE THREAD

**Issue by machuck** [tidwall/gjson#16]
I am new to golang, and am following the example in ReadMe and trying iterate / traverse a nested json, but got an error "undefined: Result". Is the following example in ReadMe a "meta" code? If so, could you give a more concrete executable example to help?

```
result := gjson.Get(json, "programmers")
result.ForEach(func(key, value Result) bool{
    println(value.String()) 
    return true // keep iterating
})

```
if I change Result to any declared variable <var>a</var>, the error becomes <var>a</var> is not a type...

**Comment by tidwall** [comment]
Hi @machuck ,

There's an error in my example code. I just now fixed it in the README.

The package name prefix `gjson` was missing in front of `Result`. Therefore Go didn't know how to resolve the `Result` type. 

It should be:

```go
result := gjson.Get(json, "programmers")
result.ForEach(func(key, value gjson.Result) bool{
    println(value.String()) 
    return true // keep iterating
})
```

Thanks for finding this issue.

**Comment by tidwall** [comment]
I'm closing this issue. Please let me know if you have any more questions. Thanks.
