### ISSUE TITLE
Parsing JSON that has backslashes in its content

### ISSUE THREAD

**Issue by Cloves23** [tidwall/gjson#160]
Hi,

I tried to parse a JSON with `\` as part of the value and noticed that all characters after the backslash are being ignored.

**Example used:**
```go
package main

import (
	"fmt"

	"github.com/tidwall/gjson"
)

func main() {
	json := `{"re": "[^\das]", "repl": "#"}`
	fmt.Println(json)
	fmt.Println(gjson.Parse(json).Value())
}
```

**Output:**
```
{"re": "[^\das]", "repl": "#"}
map[re:[^ repl:#]
```

Thanks.

**Comment by tidwall** [comment]
Hi, 

This is not valid json

```json
{"re": "[^\das]", "repl": "#"}
```

JSON requires that the backslash character is escaped 

```json
`{"re": "[^\\das]", "repl": "#"}`
```

You can programmatically check json for using the `gjson.Valid(json)` function.

**Comment by Cloves23** [comment]
Ok, sorry.
You are right.

I'm new on Golang and I thought that if I create a string using crase instead of quotes wouldn't be necessary add extra backslash, but I was wrong.

Example:
```go
\\ use
str = `\x`
\\ instead of
str = "\\x"
```
Thanks.
