### ISSUE TITLE
How to get the json i put into parameter

### ISSUE THREAD

**Issue by huangjingfang** [tidwall/gjson#170]
Hi 
     I have a problem with gjson recently. how can i get the json that I put into parameter. 
`gjson.Get(a, "?") = a`, what should "?" be

**Comment by cjkreklow** [comment]
You can use `gjson.Get(a, "@this")` to return a Result wrapping `a`, which would make `gjson.Get(a, "@this").Raw` return `a`.  You could also use `gjson.Parse(a)` instead, to achieve the same result.

**Comment by huangjingfang** [comment]
it works, many thanks!
