### ISSUE TITLE
concurrency crashes

### ISSUE THREAD

**Issue by universam1** [tidwall/gjson#173]
Hi, we are using GJSON in an application making heavy use of goroutines.

Apparently, we run into concurrency clashes causing application crashes, the error is quite clear:

```
fatal error: concurrent map writes
goroutine 4555 [running]:
runtime.throw(0x1041950, 0x15)
	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc001dc5338 sp=0xc001dc5308 pc=0x434b42
runtime.mapassign_faststr(0xecda00, 0xc000118f60, 0x102fe84, 0x1, 0x0)
	/usr/local/go/src/runtime/map_faststr.go:291 +0x3de fp=0xc001dc53a0 sp=0xc001dc5338 pc=0x41375e
github.com/tidwall/gjson.AddModifier(...)
	/go/pkg/mod/github.com/tidwall/gjson@v1.4.0/gjson.go:2612
```

Should GJSON be accessed as an instance rather? Is it thread safe at the moment per se or are its operations global hence clashing or overwriting each other?

Thanks!

**Comment by tidwall** [comment]
Unfortunately the `gjosn.AddModifier` function is not thread-safe.

```go
// AddModifier binds a custom modifier command to the GJSON syntax.
// This operation is not thread safe and should be executed prior to
// using all other gjson function.
```

I recommend adding all custom GJSON modifiers in init() or main() prior to calling the `gjson.Get`.

**Comment by tidwall** [comment]
Closing for now. Feel free to reopen if needed.
