### ISSUE TITLE
Google App Engine Support

### ISSUE THREAD

**Issue by dadatawajue** [tidwall/gjson#18]
Hi!

I would really like to use this package for a project using Google App Engine, but I get this error:

`go-app-builder: Failed parsing input: parser: bad import "unsafe" in github.com/tidwall/gjson/gjson.go from GOPATH`

I was hoping there might be an simple way to replace `unsafe.Pointer` so that it will work on App Engine?

Thanks a lot!

**Comment by tidwall** [comment]
If these lines were commented out then the "unsafe" import can be removed:
- https://github.com/tidwall/gjson/blob/master/gjson.go#L1300-L1307
- https://github.com/tidwall/gjson/blob/master/gjson.go#L1310-L1358

Doing so will also remove the `gjson.GetBytes` function, but the `gjson.Get` should still work.

**Comment by tidwall** [comment]
Hi @dadatawajue I'm closing this issue for now. Please let me know if there anything else I can help with around this issue.

**Comment by dadatawajue** [comment]
Hi, I just noticed I forgot to reply earlier; it worked, thanks a lot, really appreciate it <3

**Comment by tidwall** [comment]
@dadatawajue You're welcome. :)
