### ISSUE TITLE
Escaped double qoutes are treated as quotes in string properties

### ISSUE THREAD

**Issue by mariotoffia** [tidwall/gjson#182]
Hi and thanks for a great library! I use it to parse rather hefty amount of json in a process pipe (alike) _JSON_ model that I've invented :). Thus i have a set of operation that may take place and need for passing strings.

The problem I've encounter is that it seems to not respect _\\"_ as part of the whole string. It rather terminates at the `"` instead. So for example this expression do not work:

```json
"ODT": "[select(source, \"ObjectName == 'P1 Outs.temp.design'\")]"
```

When I try to access the property (`value.Str`) it just gives me back `select(source, "` and not the whole expression. I use it using a `ForEeach` like this

```go
	obj.ForEach(func(key, value gjson.Result) bool {
		switch key.Str {
		case "c":
			ass.C = value.Str
		case "e":
			ass.E = value.Str
		case "f":
			ass.F = value.Bool()
		case "d":
			ass.D = value.Value()
		}
		return true
	})
```

Cheers,
 Mario

**Comment by tidwall** [comment]
Hi, Could you provide a working example? I would like to reproduce the bug on my side. Thanks.

**Comment by mariotoffia** [comment]
@tidwall I think I back down on this 

Many thanks for a really good library!
