### ISSUE TITLE
how to convert  gjson object to struct

### ISSUE THREAD

**Issue by mf0324** [tidwall/gjson#193]
I have a question， I have a func have gjson object parameter，for example：

type mapJSONTest struct {
	Test map[int]int
}

func convertStruct(obj *gjson.Json) {
      // how can convert obj to mapJSONTest
     // of course  I can 
     //var gobj mapJSONTest
     // body, _ := obj.ToJson()
     //gjson.DecodeTo(body, &gobj) 
}

func main() {
	mapTest := make(map[int]int)
	mapTest[1000] = 2
	mapTest[2000] = 4
	testObj := mapJSONTest{}
	testObj.Test = mapTest

        body, _ := gjson.Encode(testObj)

        jsonObj, _ := gjson.DecodeToJson(body)

        convertStruct(jsonObj)
}

**Comment by tidwall** [comment]
There no endode/decode functions with gjson. I recommend using the standard `json` package for that kind of functionality.
