### ISSUE TITLE
Join multiple paths into key value returns [][][] ?

### ISSUE THREAD

**Issue by tiramisubliss** [tidwall/gjson#199]
Hi @tidwall,

I tried to join multiple paths but got result like this, any suggestion? Thank you in advanced
```
body, _ := ioutil.ReadAll(res.Body)
json := string(body)
data := gjson.Get(json, "results.0.series.#.tags.host:results.0.series.#.values.1.1")
fmt.Println(data.String())
```
result
[]
[]
[]

Example:
[ha-external-c-01 arango-db-a-01 ha-external-a-02]
[0.04999 0.050062 0.050025 ]

Expected:
[“ha-external-c-01”: 0.04999, “arango-db-a-01 ha-external-a-02”: 0.050062, “ha-external-a-02”: 0.050025]

**Comment by tidwall** [comment]
Can you provide the original JSON?

**Comment by tiramisubliss** [comment]
There, it belongs to these:

data := gjson.Get(json, "results.0.series.#.tags.host")
value := gjson.Get(json, "results.0.series.#.values.1.1")

```
["ha-external-c-01","arango-a-01","ha-external-a-01"]

[0.025000000,0.0750750,0.0500253]
```

the original one you can see at this [link](https://jsonblob.com/ed177118-5d08-11eb-93f7-07e3c2dc3ed0)

**Comment by tidwall** [comment]
Here's a way to do it with gjson/sjson

package main

import (
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

func main() {
	datas := gjson.Get(json, "results.0.series.#.tags.host").Array()
	values := gjson.Get(json, "results.0.series.#.values.1.1").Array()
	var out string
	for i := 0; i < len(datas) && i < len(values); i++ {
		out, _ = sjson.Set(out, datas[i].String(), values[i].Float())
	}
	println(string(out))
}
// output: 
// {"ha-external-01":0,"ha-external-03":0.22579026592537219}

**Comment by tiramisubliss** [comment]
Cool, thanks for your help @tidwall

**Comment by tidwall** [comment]
You're welcome. :)
