### ISSUE TITLE
If one key is having other key value as a prefix, getManyBytes function is returning wrong values

### ISSUE THREAD

**Issue by Poorva17** [tidwall/gjson#20]
**Sample test case** :

package main_test

import (
	"testing"
	"github.com/tidwall/gjson"
	"github.com/stretchr/testify/assert"
)

func Test_GJson(t *testing.T) {
	result := gjson.GetManyBytes([]byte(sampleJSON), "name", "name1", "address", "addressDetails")
	expectedValues := []string{"FirstName", "FirstName1", "address1", "address2"}
	assert.Equal(t, expectedValues[0], result[0].String())
	assert.Equal(t, expectedValues[1], result[1].String())
	assert.Equal(t, expectedValues[2], result[2].String())
	assert.Equal(t, expectedValues[3], result[3].String())
}

const sampleJSON = `{
               "name": "FirstName",
               "name1": "FirstName1",
               "address": "address1",
               "addressDetails": "address2",
}`

----------------------------------------------------------------------------------------------------

Explanation  : This test case is failing. It gives "FirstName" as a value for both keys "name" and "name1". If one key is present as a prefix in other key, GetManyBytes function is returning wrong values.

**Comment by tidwall** [comment]
@Poorva17 Thank you very much for reporting this issue.
