### ISSUE TITLE
Assistance pulling data from an array

### ISSUE THREAD

**Issue by brett0701** [tidwall/gjson#201]
I have the below json data and need to check if the "WorkStartDate" exists and if so obtain the value data that is associated with it.  What is the best way of accomplishing this?

{
  "normalized": {
    "id": "13991",
    "subject": "ABC",
    "description": "This is a test",
    "customFields": [
      {
        "name": "SiteContact:Name"
      },
      {
        "name": "SiteContact:Phone"
      },
      {
        "name": "AlternateContact:Phone"
      },
      {
        "name": "NextFollowUp",
        "value": "2021-01-21T05:00:00Z"
      },
      {
        "name": "NextActionRequired",
        "value": "Nothing"
      },
      {
        "name": "WorkStartDate",
        "value": "Wed Jan 20 00:00:00 2021"
      },
      {
        "name": "WorkEndDate",
        "value": "Mon Jan 25 17:00:00 2021"
      }
    ]
  }
}

Thanks in advanced for your help.

**Comment by tidwall** [comment]
normalized.customFields.#(name="WorkStartDate").value

**Comment by brett0701** [comment]
Thanks Josh. I appreciate the quick response.

**Comment by tidwall** [comment]
You’re welcome. 🙂

**Comment by tidwall** [comment]
I'm closing this issue for now. Please feel free to reopen if you have further questions.
