### ISSUE TITLE
Query syntax - is #(...) really supported

### ISSUE THREAD

**Issue by shmul** [tidwall/gjson#202]
Hi,

I tried using the `#(...)` query syntax as document but it doesn't work for me (version v1.6.7). The older `#[..]` syntax does work but you mentioned it will be deprecated. Is the new one already supported?
These are the examples from running my tests (using `gjson.GetManyBytes` on the documentation example json)

```
friends.#[last=="Murphy"]#.first
[["James"]]

friends.#(last=="Murphy")#.first
[]
```
Am I missing something?

Cheers,
Shmul

**Comment by tidwall** [comment]
Yes. It works.

**Comment by shmul** [comment]
Thanks for the prompt response. Indeed it does - https://play.golang.org/p/F41yssCMxcU . 
Sorry. I can swear it didn't work for me earlier 🤷‍♂️ .
Thanks anyway
