### ISSUE TITLE
Help with array

### ISSUE THREAD

**Issue by chno2016** [tidwall/gjson#204]
I have an array but with diferent name, so How I can get that name and the array?

Example

{
"Departamentos": [{
                    "Deportes": [{
                            "Nombre": "Aurora"
                        },
                        {
                            "Nombre": "Amador"
                        },
                        {
                            "Nombre": "Armados"
                        }
                    ]
                },
                {
                    "Comida": [{
                        "Nombre": "A comer todo",
                    }]
                },
                {
                    "Celulares": []
                }
            ]

}

So I searching something like that:

value :=gjson.Get(json, "SomethingLOL")
and value= [Deportes, Comida, Celulares]

**Comment by aihanjiao** [comment]
### if you only using `github.com/tidwall/gjson` in golang:
``` golang
package main

import (
	"fmt"
	"github.com/tidwall/gjson"
)

var str = `{
"Departamentos": [{
"Deportes": [{
"Nombre": "Aurora"
},
{
"Nombre": "Amador"
},
{
"Nombre": "Armados"
}
]
},
{
"Comida": [{
"Nombre": "A comer todo",
}]
},
{
"Celulares": []
}
]

}`

func main() {
	var data []string
	t := gjson.Parse(str)
	for _, v := range t.Get("Departamentos").Array() {
		data = append(data, getKeys(v.Map())...)
	}
	fmt.Println(data)
}

func getKeys(m map[string]gjson.Result) []string {
	j := 0
	keys := make([]string, len(m))
	for k := range m {
		keys[j] = k
		j++
	}
	return keys
}
```

``` bash
output:
[Deportes Comida Celulares]
```
### should be confirmed json data what does it look like at first
`https://www.json.cn`
<img width="1263" alt="截屏2021-05-02 01 18 07" src="https://user-images.githubusercontent.com/59612542/116789940-4281cb80-aae4-11eb-9e16-ad0e89a56f4b.png">
