### ISSUE TITLE
How to get items with specific index?

### ISSUE THREAD

**Issue by susonsapkota** [tidwall/gjson#205]
For now I am iterating over the ```Result``` to get items.
```go
gjson.Result.ForEach(func(key, value gjson.Result) bool {
    println(value.raw)
    return true
})
```
Is there any way I can get items from specific index without iterating over all the list? Or way to get only first item or last item?

**Comment by tidwall** [comment]
Yes, for arrays you can use the index number

```go
json := `{"a":[10,20,30,40]}`
println(gjson.Get(json, "a.2").String()) // prints "30"
`

**Comment by susonsapkota** [comment]
Thanks this worked.
