### ISSUE TITLE
Regression defect introduced by fix of https://github.com/tidwall/gjson/issues/20 

### ISSUE THREAD

**Issue by Poorva17** [tidwall/gjson#21]
commit id of fix - **https://github.com/tidwall/gjson/commit/256887a8aad21f227053cbd1136842ac9e93d5c8**
This fix has introduced regression defect.

Current sample failing test case:

package main_test

import (
"testing"
"github.com/tidwall/gjson"
"github.com/stretchr/testify/assert"
"fmt"
)

func Test_GJson(t *testing.T) {
result := gjson.GetManyBytes([]byte(sampleJSON), "Level1Field1", "Level1Field2.Level2Field1", "Level1Field2.Level2Field2.Level3Field1", "Level1Field4")
assert.Equal(t, "3", result[0].String())
assert.Equal(t, expectedValue1, result[1].String())
assert.Equal(t, expectedValue2, result[2].String())
assert.Equal(t, "4", result[3].String())
}

const expectedValue1 = [ "value1", "value2" ]

const expectedValue2 = [ { "key1":"value1" } ]

const sampleJSON = { "Level1Field1":3, "Level1Field4":4, "Level1Field2":{ "Level2Field1":[ "value1", "value2" ], "Level2Field2":{ "Level3Field1":[ { "key1":"value1" } ] } } }

**Comment by tidwall** [comment]
@Poorva17 I just pushed a fix to the master branch. Thanks!
