### ISSUE TITLE
Incorrect edge cases for gjson.Valid()

### ISSUE THREAD

**Issue by WillAbides** [tidwall/gjson#210]
I ran test_parsing from https://github.com/nst/JSONTestSuite against `gjson.Valid()` and discovered a couple of edge cases that gjson incorrectly calls valid.

`[-]` from [n_array_just_minus.json](https://github.com/nst/JSONTestSuite/blob/d64aefb55228d9584d3e5b2433f720ea8fd00c82/test_parsing/n_array_just_minus.json)

and 

`[-.123]` from [n_number_neg_real_without_int_part.json](https://github.com/nst/JSONTestSuite/blob/d64aefb55228d9584d3e5b2433f720ea8fd00c82/test_parsing/n_number_neg_real_without_int_part.json)

To be clear, this isn't a problem for me. I'm just reporting it because I thought you might want to know.

**Comment by tidwall** [comment]
> To be clear, this isn't a problem for me.  I'm just reporting it because I thought you might want to know.

That's super kind of you. Thank you for reporting! :)
