### ISSUE TITLE
Could you indicate why the latest release is not pointing to the actual latest release?

### ISSUE THREAD

**Issue by 030** [tidwall/gjson#219]

**Comment by tidwall** [comment]
The current release is [v1.8.0](https://github.com/tidwall/gjson/tree/v1.8.0) and I'm not seeing any issues on my side.

Can you provide more details of what is happening, or how to reproduce this issue?

**Comment by 030** [comment]
![image](https://user-images.githubusercontent.com/7524528/121069743-23a2e300-c7ce-11eb-8056-5e707426be01.png)
