### ISSUE TITLE
Defaults for Nil Case

### ISSUE THREAD

**Issue by genexp** [tidwall/gjson#22]
Hey all - absolutely love this library. We use it extensively in our server platform. We do a ton of nil catching, since our marshaller converts then to "null". I was wondering if there had been any thought to allowing a default value that could be used if a value isn't found.

**Comment by tidwall** [comment]
Thanks and I'm happy to hear that you find the library useful.

The default `gjson.Result{}` value currently represents a non-existent json member. You can use the `result.Exists()` function to see if the member exists, and if it does you can use `if result.Type == gjson.Null` to check if the value is `null` of something else.

Here's some examples:

```go
result := gjson.Get(`{"first":"Jane","last":"Austen"}`, "last")
println(result.Exists())  // true
println(result.Type)      // gjson.String
```

```go
result := gjson.Get(`{"first":"Jane","last":null}`, "last")
println(result.Exists())  // true
println(result.Type)      // gjson.Null
```

```go
result := gjson.Get(`{"first":"Jane"}`, "last")
println(result.Exists())  // false
println(result.Type)      // gjson.Null
```

**Comment by genexp** [comment]
Thanks @tidwall In hindsight, this was kind of a silly request.  I'll just wrap this up in a function on our end.  Ideally I'd like it to work like:

```
result, err := gjson.GetWithDefault(`{"first":"Jane","last":null}`, "last", "foo")
println(err)  // nil
println(result.Exists())  // true
println(result.Type)      // gjson.String
println(result)      // "foo"
```

```
result, err := gjson.GetWithDefault(`{"first":"Jane"}`, "last", "foo")
println(err)  // NoValueError
println(result.Exists())  // false
println(result.Type)      // gjson.String
println(result)      // "foo"
```

We use this to parse JSON, and we often find edge cases with missing data, or things we didn't understand.  We'd like to be able to default basically everything to a known JSON string, and have it be parsed like it existed.

**Comment by tidwall** [comment]
Not a silly request at all. I think your solution to wrap it in a function is a good one.
