### ISSUE TITLE
Non strict mode

### ISSUE THREAD

**Issue by 89z** [tidwall/gjson#235]
I am trying to parse JSON from some input like this:

~~~js
window.__additionalDataLoaded('extra',{"shortcode_media":999});
~~~

Where the output would be:

~~~json
{"shortcode_media":999}
~~~

is something like that possible? Similar to `Strict = false` with XML:

https://godocs.io/encoding/xml#Decoder.Strict

**Comment by 89z** [comment]
?

**Comment by 89z** [comment]
@tidwall why are you closing issues with no comment?

**Comment by tidwall** [comment]
I noticed that you asked the exact same question in over a dozen other repos.

https://github.com/search?l=Go&o=desc&q=%22Non+strict+mode%22&s=updated&type=Issues

You even asked the same question in [another one of my repos](https://github.com/tidwall/pjson).

And it looks like you got some answers, some [free code](https://github.com/WillAbides/rjson/issues/47#issuecomment-930576865), and you also started a [project](https://github.com/89z/parse) to solve your problem.

You have the answer. You have the code.

> why are you closing issues with no comment?

Github provides you with a tool to spam questions. And it provides me with a close button.

**Comment by 89z** [comment]
> I noticed that you asked the exact same question in over a dozen other repos.
>
> https://github.com/search?l=Go&o=desc&q=%22Non+strict+mode%22&s=updated&type=Issues

@tidwall so rather than just read and answer the original posted issue, you took it upon yourself to to detective work on me? Why? Why not just look at the question as is, then answer (or say youre too busy, are arent interested, or whatever). Why take it upon yourself to stalk a person asking a question?

> And it looks like you got some answers, some [free code](https://github.com/WillAbides/rjson/issues/47#issuecomment-930576865), and you also started a [project](https://github.com/89z/parse) to solve your problem.

This is creepy behavior, and you should stop it.

> You have the answer. You have the code.

Please dont tell me what I have and dont have. I can make that assessment for myself.

> Github provides you with a tool to spam questions. And it provides me with a close button.

If 99 similar repos are online, I am within my right to post any issue that I like. If the owner of a repo like it, then they can work with me. If they want to be creepy stalker (like you), then they can do what you did.

**Comment by tidwall** [comment]
Steven, I closed the issue and you asked this:

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/1156077/135724416-0eb1dd1c-a9f9-4178-9300-b81ce8f88d53.png">

So I answered. Then you deleted the your question and called me a creepy stalker. That's f*cked up behavior and I'm reporting you.
