### ISSUE TITLE
awesome-go and code complexity issues

### ISSUE THREAD

**Issue by fiatjaf** [tidwall/gjson#24]
Hello, library maintainers. 

I was trying to include this fantastic library on [awesome-go](https://github.com/avelino/awesome-go), but I'm running in some problems there with some code quibbles that could be easily changed.

Would you please take a look at https://github.com/avelino/awesome-go/pull/1363 good eyes and no prejudices?

**Comment by tidwall** [comment]
Hi @fiatjaf, 

Thanks for requesting to have gjson added to awesome-go. I just updated the `gjson_test.go` file to reduce some complexity and this bumped the gocyclo to 50%. Do you think that that's good enough? I would think an overall grade of A+ should suffice.

**Comment by fiatjaf** [comment]
Thanks, @tidwall!

I don't know. Let's hope so.

**Comment by joeybloggs** [comment]
@fiatjaf @tidwall a little more test coverage to meet the 90% test coverage requirements for data related packages and it should be good to Go!

https://github.com/avelino/awesome-go/pull/1363#issuecomment-293267146

**Comment by tidwall** [comment]
Thanks @fiatjaf! I just pushed an update that brings the [coverage](http://gocover.io/github.com/tidwall/gjson) above 90%. Let me know if there's anything else.
