### ISSUE TITLE
Query last item of array

### ISSUE THREAD

**Issue by itmaple** [tidwall/gjson#244]
Why not make `-1` to get the last item?  such as sjson sjson.Set(json, "-1"...)

**Comment by tidwall** [comment]
I can see that being useful and something I'll consider.

**Comment by tidwall** [comment]
Thinking about it further. In SJSON, if `-1` **adds** an element and in GJSON `-1` requests the last element, then I could see that being confusing to the developer. 

A solution may require a little more thought, but right now using the `@reverse` modifier can effectively give a similar result.

Take this JSON with these paths for example:

```json
["a","b","c","d"]
```

```
"@reverse.0"    -> "d"
"@reverse.1"    -> "c"
```

As far as the `@index` modifier idea, perhaps that something worth considering in the future.

**Comment by itmaple** [comment]
Yeah, thank you! I will close the comment!
