### ISSUE TITLE
Can Array.Foreach key=array.index?

### ISSUE THREAD

**Issue by itmaple** [tidwall/gjson#248]
```
array.ForEach(func(key, value gjson.Result) bool {
    // key -> 0 or 1 or 2 ...
}
```

**Comment by tidwall** [comment]
Yes. I think that this can be made so. While an array does not really have a key like an object, we can easily produce one behind the scenes. 

I think for now we should only fill the `key.Num` and `key.Type` fields. We'll leave the `key.Raw` and others empty.

This'll allow for `key.String()` and `key.Int()` to return the string and integer representation of the array index.

**Comment by tidwall** [comment]
I just added this feature. Thanks for the suggestion.

**Comment by itmaple** [comment]
Yep!Thanks.
