### ISSUE TITLE
anonymous array - bug?

### ISSUE THREAD

**Issue by pavel-pimenov** [tidwall/gjson#266]
<pre>
package main

import "github.com/tidwall/gjson"

const json = `{
   [
    {
      "firstName": "Janet", 
      "lastName": "McLaughlin", 
    }, {
      "firstName": "Elliotte", 
      "lastName": "Hunter", 
    }, {
      "firstName": "Jason", 
      "lastName": "Harold", 
    }
  ]
}`

func main() {
	result := gjson.Get(json, "*")
	for _, name := range result.Array() {
		println(name.String())
	}
}

</pre>

output

Janet

Program exited.

https://go.dev/play/p/76doyDkWyn3

**Comment by tidwall** [comment]
Your json isn't valid. The array is nested in an object, but there is no key associated with the array. All object members should have one key for each value.

Your options are:

Make sure the json has a key.

```json
{
  "my_key": [
    {
      "firstName": "Janet", 
      "lastName": "McLaughlin", 
    }, {
      "firstName": "Elliotte", 
      "lastName": "Hunter", 
    }, {
      "firstName": "Jason", 
      "lastName": "Harold", 
    }
  ]
}
```

Or, use the `@valid` modifier to ensure that gjson validates the invalid json prior to returning results.

```
result := gjson.Get(json, "@valid.*")
```
