### ISSUE TITLE
"tag_name" is not successfully parsed

### ISSUE THREAD

**Issue by Bellisario** [tidwall/gjson#289]
I was trying to parse from latest GitHub releases, but I had a problem parsing "tag_name".
Is this supported? Am I doing something wrong?

---
Here is a piece of what I'm trying to do:
```go
var latestRaw = gjson.Get("{tag_name: \"1.1.0\"}", "tag_name").String()
// latestRaw is an empty string
 ```

**Comment by spike014** [comment]
@Bellisario 
You lost `""` between `tag_name`

```go
package main

import (
	"fmt"

	"github.com/tidwall/gjson"
)

func main() {
	var latestRaw = gjson.Get("{\"tag_name\": \"1.1.0\"}", "tag_name").String()
	fmt.Println(latestRaw)
}
```

```shell
go run xxx.go
1.1.0
```

**Comment by Bellisario** [comment]
@spike014 thanks!
I didn't realize I was missing double quotes... :disappointed: 
I'll close the issue!
