### ISSUE TITLE
Parsing of large integer ids is broken: integers should remain integers

### ISSUE THREAD

**Issue by joelpresence** [tidwall/gjson#29]
Hi,

Thanks for making this great library available!

There is a flaw when parsing large integer ids.  It's common in REST APIs to use large integer ids for entity ids - often they encode time info in them, and they have nothing to do with an RDB autoincrement sequence.

In this case, gsjon is parsing those JSON integers into float64, and the precision of the id is being lost, rendering it useless.  JSON integers should be parsed into int64 not float64.  I know that the default go json package also parses all numbers into float64, but that also feels wrong to me.  JSON says nothing about numerical types only that they could be integers or floats, and JSON parsing in most other languages like Ruby, Objective-C, etc., will choose the correct numerical type in the language based on the observed type of the literal (e.g. 6.2 would be a float but 6 would be an integer) and the type of the field's values can vary from one record to another: the same field could be a float from a literal of 6.2 but an integer from a float of 6.

Here's an example in go using gjson:
```
jsonString := `{"IdentityData":{"GameInstanceId":634866135153775564}}`
value := gjson.Get(jsonString, "IdentityData.GameInstanceId")

// gjson has stored value as float64 and any use of it seems to produce
// 634866135153775616.0, which is the wrong id and
// even gjson.GetBytes([]byte(jsonString), "IdentityData.GameInstanceId")) prints as
// a float64 634866135153775616.0

// This seems to be the only way to get the correct id
gameInstanceIdString := gjson.Get(jsonString, "IdentityData.GameInstanceId").Raw
gameInstanceId, errGameInstanceId := strconv.ParseInt(gameInstanceIdString, 10, 64)
if errGameInstanceId != nil {
  // We can use gameInstanceId and it will be the correct value of 634866135153775564
}
```
That is pretty cumbersome just to get an integer id out of some json.  I love gjson - it's well-designed and a breeze to use, but having to do all this just to preserve the true value of an integer id makes gjson a lot less compelling.

Am I missing something here?  Is there an easier way to do this?

If this was some kind of large measurement or something, I guess the imprecision/rounding wouldn't be as big a deal.  But this is an id, and `634866135153775616` is not useful when we really need the true value `634866135153775564`.

Any help would be hugely appreciated!

**Comment by joelpresence** [comment]
It turns out you can invoke [UseNumber](https://golang.org/pkg/encoding/json/#Decoder.UseNumber) on the go `json.Decoder` to preserve numbers as `interface{}` so you wouldn't need to store them as `float64` and could preserve the actual type of the literal.

Thoughts?

Thanks!

**Comment by tidwall** [comment]
Thanks a ton for bringing this to my attention. 

I just reviewed the JSON RFC and you're right, there is no requirement for how a parser should interpret a number. It only makes a soft recommendation to use IEEE754.

The original design was based around the standard Go json package, which treats all numbers as floats, and I decided early on to keep that same behavior. Clearly that decision was wrong.

This is tricky because the `Result.Num` field is a float64, and it's automatically filled following a `Get()` call. Some users of GJSON may access this field directly rather than call the `Int()`, `Uint()`, and `Float()` functions. So I don't want to change the behavior of the struct fields cause I don't want to break things. 

But I think I might be able to do some magic behind the `.Int()` and `.Uint()` functions to inspect the Num and Raw data and pull out the correct values.

I'll do some experimentations and let you know ASAP.

**Comment by joelpresence** [comment]
You're welcome @tidwall !  And thanks for taking a look at this.  :-)

**Comment by tidwall** [comment]
I just pushed an update that should now work correctly when calling the `result.Int()` or `result.Uint()` functions. Please let me know if you run into any additional problems. 

Thanks again for your help.

**Comment by joelpresence** [comment]
Wow, that was fast!  Thank you!  :-) I'll be sure to pull and test in the morning and star your repo.

Best,

Joel

Sent from my iPhone

On May 25, 2017, at 7:42 PM, Josh Baker <notifications@github.com<mailto:notifications@github.com>> wrote:


I just pushed an update that should now work correctly when calling the result.Int() or result.Uint() functions. Please let me know if you run into any additional problems.

Thanks again for your help.

**Comment by joelpresence** [comment]
@tidwall I just pulled the latest version and I can confirm that this fix works.  Thanks so much for fixing this and I'm especially grateful for the quick turnaround.  This is a great library.  Repo starred.  :-)

Thanks!

**Comment by tidwall** [comment]
That's great to hear. :)

**Comment by icankeep** [comment]
Hello, the performance of this code does not seem to be as expected.

```go
func TestPrecisionLost(t *testing.T) {
	json := `{
		"ID": 12345678910111215
	}`
	// print 1.2345678910111216e+16
	fmt.Println(Get(json, "ID").Value())
}
```


I wonder if the value should be converted to int64 first in the Value() method? And just like this:
<img width="1032" alt="image" src="https://github.com/tidwall/gjson/assets/39434627/a4f0113d-e0be-4d6c-85da-653e362abde4">
