### ISSUE TITLE
JSON only get keys in first level

### ISSUE THREAD

**Issue by orhan-erday** [tidwall/gjson#297]
I need to print all first level keys from JSON, how can I do this?

Example:
```
json := `{
            "data": {
                "first": {
                    "second": [
                        1,
                        2,
                        3,
                        4
                    ]
                },
                "staleData": null
            }
        }`
printFirstLevelKeys(json) // this method should print all first level keys.
```
***output***
`$ data, first, second`

**Comment by volans-** [comment]
@orhan-erday From your example it seems to me that you want to extract the "first" key for each nested object, but the JSON specification states that `An object is an unordered set of name/value pairs` ([source](https://www.json.org/json-en.html)),  so there is no concept of "first" key in an object and it's implementation-dependent.

That said I guess you could leverage the `@keys` modifier in a recursive way.
- `@keys.0` gives you `"data"`
- `data.@keys.0` gives you `"first"`
- `data.first.@keys.0` gives you `"second"`
- `data.first.second.@keys.0` gives you `null` that tells you to stop the recursion.

In case you know in advance the number of nested layers your object has, then you could leverage the `@values` modifier and generate dynamically a multipath query:
`[@keys.0,@values.0.@keys.0,@values.0.@values.0.@keys.0]`
that would give you:
`["data","first","second"]`

**Comment by orhan-erday** [comment]
Thank you so much!
