### ISSUE TITLE
Nested slice return error

### ISSUE THREAD

**Issue by huangpeizhi** [tidwall/gjson#3]
fmt.Println(gjson.Get(jstr, "areas.2.points.#"))  

output : 7 ? why?

jstr sample:

{
    "areas":[
        {
            "name":"南站区域",
            "type":"circle",
            "lon":113.26342,
            "lat":22.99095,
            "radius":0.47
        },
        {
            "name":"省市站区域",
            "type":"circle",
            "lon":113.24723,
            "lat":23.15074,
            "radius":0.21
        },
        {
            "name":"火车站公交总站区域",
            "type":"polygon",
            "points":[
                {
                    "lon":113.251895,
                    "lat":23.150811
                },
                {
                    "lon":113.254116,
                    "lat":23.150811
                },
                {
                    "lon":113.254116,
                    "lat":23.148808
                },
                {
                    "lon":113.251895,
                    "lat":23.148808
                }
            ]
        }
    ]
}

**Comment by tidwall** [comment]
Just fixed this issue. Thanks a bunch for letting me know.
