### ISSUE TITLE
How can I get the root arrays with gjson?

### ISSUE THREAD

**Issue by Akagi201** [tidwall/gjson#31]
The body content is
```
[
{
    "client_id": 1000,
    "edge_ip": "xx.xx.xx.xx",
    "edge_port": port1,
    "timestamp":123456
},
{
    "client_id": 1001,
    "edge_ip": "yy.yy.yy.yy",
    "edge_port": port2,
    "timestamp":123456
}
]
```
How can I get all the objects through like this: `gjson.Get(body, "*").Array()`?

**Comment by Akagi201** [comment]
Parse

**Comment by m247support** [comment]
@Akagi201 what was the fix?

**Comment by m247support** [comment]
gjson.Parse(json)

**Comment by ebob9** [comment]
Sorry for resurrecting this thread, but it's a top result searching for "gjson get root of document" etc.  

For anyone else who finds this thread, the `gjson.Parse(json)` above works great. But if you want to use `gjson.Get` for any specific reason, you can use the `@this` modifier in 1.2+ to get the root. For example: `gjson.Get(json, "@this")`

This is great for running it through other modifiers (like `@pretty`): `gjson.Get(json, "@this|@pretty")`.

There might be a way to chain modifiers with `gjson.Parse`, but I couldn't figure it out. Doing the `Get` and using `@this` method made it simple.
