### ISSUE TITLE
how to get a data that his name is like "test.test2"

### ISSUE THREAD

**Issue by kosmosCosmos** [tidwall/gjson#32]
gjson.parse("XXX").Get("test.test1") this will be convert to gjson.parse("XXX").Get("test").get("test1")

**Comment by tidwall** [comment]
Hi @kosmosCosmos,

You should be able to get data from a JSON payload using `gjson.Get()`

For example, if your payload is:

```json
{
  "test": {
    "test2": "Hello"
  }
}
```

```go
result := gjson.Get(payload, "test.test2")
println(result.String())
```

will output:

```
Hello
```

Optionally you can use the `gjson.Parse()` function. 
All of the following will return the same value:

```go
gjson.Get(payload, "test.test2")
gjson.Get(payload, "test").Get("test2")
gjson.Parse(payload).Get("test.test2")
gjson.Parse(payload).Get("test").Get("test2")
```

**Comment by kosmosCosmos** [comment]
maybe you dont understand my mind 
my mean is this:
```go
a json like 
{
  "datas": {
    "A.B": [
      5872
    ],
    "B.c": [
      111
    ],
    "C.D": [
      0,
      4737
    ]
  }
}
```
i dont know A.B,B.C,.C.Dwhich is the first. I need to search A.B .but when I use gjson.parse("XXX").Get("datas.A.B") it will convert  gjson.parse("XXX").Get("datas.A").Get(B).
how could I can find a data like A.B ?
thanks a lot

**Comment by tidwall** [comment]
The README states:

> The dot and wildcard characters can be escaped with '\'.

Access `A.B` like such:

```
gjson.Get(payload, "datas.A\.B")
```

**Comment by tidwall** [comment]
I'm closing this for now. Please reopen if you have further question around this issue. Thanks.

**Comment by luisdavim** [comment]
I get `unknown escape sequence` when using:
```
gjson.Get(payload, "datas.A\.B")
```
