### ISSUE TITLE
Support empty paths

### ISSUE THREAD

**Issue by becheran** [tidwall/gjson#322]
Are empty paths are also supported? I don't really find an answer to the question in the path documentation. The following test fails for me, but I would have expected it to succeed if empty paths would have been allowed? I Would have expected that for empty paths the full json payload would be interpreted.

``` go
func TestEmptyPath(t *testing.T) {
    testrunner.UnitTest(t, func() {
        res := gjson.Get(`["foo"]`, "")
        if !res.Exists(){
            t.Fail()
        }
    })
}
```

**Comment by tidwall** [comment]
An empty path is valid and will return the value for an empty key in an object.

```go
gjson.Get(`{ "": "hi" }`, "").String() == "hi"
gjson.Get(`{ "": { "inner": "hi" } }`, ".inner").String() == "hi"
```

**Comment by becheran** [comment]
@tidwall ah got it. Thx for the fast response and clarification!
