### ISSUE TITLE
Iterating only first N items in an array

### ISSUE THREAD

**Issue by jmakov** [tidwall/gjson#326]
The README mentions iterating through the array using `ForEach`. I'm wondering if there's a way to iterate only through the first N items in the array. Or would that include a counter and an if statement in the `ForEach` loop? E.g. how would it look like to iterate through the first 5 items in a json document of the form `{data: [[2.3, 3.2], [1,2], ... ]]}`?

**Comment by volans-** [comment]
This looks very similar to #302. Does one of the proposed solutions there works for you?

**Comment by jmakov** [comment]
Thanks for the quick feedback! I somehow missed that issue. Closing this one.
