### ISSUE TITLE
pretty modifiers are not working as expected

### ISSUE THREAD

**Issue by 15083787153** [tidwall/gjson#328]
### this is my code

```
package main
import (
	"fmt"
	"github.com/tidwall/gjson"
)
func main() {

	myStr := `{
    "type": "bundle",
    "id": "bundle--184272f8-fecd-4e23-96b3-c8650e78a5d1",
    "spec_version": "2.0",
    "objects": ["type": "bundle","id": "bundle--184272f8-fecd-4e23-96b3-c8650e78a5d1"]}`

	//first test
	myStr = gjson.Get(myStr, "@pretty:{\"Indent\":\"    \"} ").String()
	fmt.Println(myStr)

	//second test
	myStr = gjson.Get(myStr, `@pretty:{"Indent":"    "}`).String()
	fmt.Println(myStr)
}

```

I would like to have four spaces, but in both test results, there are only the default two spaces. Looks like the Indent parameter doesn't work。

**Comment by tidwall** [comment]
try: `@pretty:{"indent":"    "}`   (the "indent" has a lowercase 'i')

**Comment by praveen0raj** [comment]
> 
@15083787153  FYI: you have mentioned key "objects" as an array([]), but It should be with {} . After running above code, its giving wrong output.
