### ISSUE TITLE
forEach fo current json string

### ISSUE THREAD

**Issue by baxiry** [tidwall/gjson#338]
I can't use ForEach via json fields. Because it's not gjson.Result type.
Currently using this trick to convert Json string to Resolute type.
```go
data := `{"a": 1, "b": 2}`
 result := gjson.Get(`{"obj":`+data+`}`, "obj")
      result.ForEach(func(k, v gjson.Result) bool {
            // ...
            return true 
 })
```
I'm looking for a better way to get the same result.
my
any idea ? 
thank you

**Comment by baxiry** [comment]
Perhaps we need a function that operates directly on the string in order to reduce the steps and avoid repetition

**Comment by tidwall** [comment]
Use the gjson.Parse function which converts a JSON string to a gjson.Result.

```go
obj := `{"a": 1, "b": 2}`
gjson.Parse(obj).ForEach(func(k, v gjson.Result) bool {
        // ...
        return true 
})
```

**Comment by tidwall** [comment]
Optionally you can use `@this` 

```go
obj := `{"a": 1, "b": 2}`
result := gjson.Get(obj, "@this")
result.ForEach(func(k, v gjson.Result) bool {
            // ...
            return true 
})
```

**Comment by baxiry** [comment]
Wow! so thanks @tidwall

**Comment by tidwall** [comment]
You're welcome.
