### ISSUE TITLE
How to differentiate between Object and Array?

### ISSUE THREAD

**Issue by martin-flaregames** [tidwall/gjson#34]
After playing around with the library I tried to write a simple recursive JSON document visualizer, in order to do this I wanted to rely on the return values of `gjson.Result.Type()` but there is no differentiation for Object or Array there, only JSON.

The question is, how can I determine if a Result is an Array or an Object? Just calling `Array()` or `Map()` and checking the result does not seem to be the right way.

I may be missing something fundamental as well. Any pointers in the right direction will be greatly appreciated.

**Comment by tidwall** [comment]
Hi @martin-flaregames 

The best way to differentiate between an Object and Arrray is to look at the first character of the Raw field. 

```go
if result.Type == gjson.JSON {
    if result.Raw[0] == '[' {
        // ... Array
    } else {
        // ... Object
    }
}
```

**Comment by martin-flaregames** [comment]
Thanks! to does the trick. 

An improvement could be to append something like `isArray()` and  `isObject()` in order to hide this implementation detail from the user. 

You may close this ticket if you wish.

**Comment by tidwall** [comment]
You're welcome and thanks for the suggestion!

**Comment by tidwall** [comment]
FYI, I just pushed an update which adds the `IsArray()` and `IsObject()` functions.
