### ISSUE TITLE
How to pick up specific values from array of objects into target array of objects?

### ISSUE THREAD

**Issue by manmohantarle** [tidwall/gjson#343]
Hello @tidwall 

I want to get values for some keys from an array of objects and resulting value should also be array of objects with specified keys,

as per given below, 
source

> [
{
  "name": "tom",
  "age":37,
  "children": ["Sara","Alex","Jack"],
  "fav.movie": "Deer Hunter"
},
{
  "name": "riddle",
  "age":45,
  "children": ["Json","James","Jill"],
  "fav.movie": "Saw"
}
]

target json
> [
{
  "name": "tom",
  "children": ["Sara","Alex","Jack"]
},
{
  "name": "riddle",
  "children": ["Json","James","Jill"]
}
]

how can I achieve this?

**Comment by volans-** [comment]
You can achieve that with multipaths (see
https://github.com/tidwall/gjson/blob/master/SYNTAX.md#multipaths ):

```
#.{name,children}
```

**Comment by manmohantarle** [comment]
that worked, thank you @volans-
