### ISSUE TITLE
How to get values from .Array() from nested object all in one go

### ISSUE THREAD

**Issue by fracasula** [tidwall/gjson#347]
Given this small example:

```go
func TestParsing(t *testing.T) {
	data := `[{
		"workspaces": {
			"wc-1": {
				"updatedAt": "2009-11-17T20:34:58.651387237Z"
			},
			"wc-2": {
				"updatedAt": "2009-11-21T20:34:58.651387237Z"
			},
			"wc-3": {
				"updatedAt": "2009-11-19T20:34:58.651387237Z"
			}
		}
	}]`
	result := gjson.Get(data, "#.workspaces.@values.#.updatedAt")
	if len(result.String()) > 0 {
		result = gjson.Get(result.String(), "0.@values")
	}
	for _, v := range result.Array() {
		t.Log(v.String())
	}
}
```

I get the correct output:
```
=== RUN   TestParsing
    parsing_test.go:195: 2009-11-17T20:34:58.651387237Z
    parsing_test.go:195: 2009-11-21T20:34:58.651387237Z
    parsing_test.go:195: 2009-11-19T20:34:58.651387237Z
--- PASS: TestParsing (0.00s)
```

I find it hard to figure out how to do it in one go though.

These do not seem to work:
* `#.workspaces.@values.#.updatedAt.0.@values`
* `#.workspaces.@values.#.updatedAt.@values`
* `#.workspaces.@values.#.updatedAt.#.@values`

Can you help please?

**Comment by volans-** [comment]
@fracasula if you have one of the latest releases of GJSON you can use the new `@dig` modifier (see [SYNTAX.md](https://github.com/tidwall/gjson/blob/master/SYNTAX.md#modifiers)):

```
@dig:updatedAt
```

or, using the standard approach you can use (see the [Dot vs Pipe](https://github.com/tidwall/gjson/blob/master/SYNTAX.md#dot-vs-pipe) section of the syntax docs):
```
#.workspaces.@values.#.updatedAt|0
```

In both cases they return:
```
["2009-11-17T20:34:58.651387237Z","2009-11-21T20:34:58.651387237Z","2009-11-19T20:34:58.651387237Z"]
```

**Comment by fracasula** [comment]
Right, that makes sense, thanks @volans-! :+1:
