### ISSUE TITLE
Validating JSON

### ISSUE THREAD

**Issue by martin-flaregames** [tidwall/gjson#35]
The documentation tells us that

> This function expects that the json is well-formed. Bad json will not panic, but it may return back unexpected results. When the value is found it's returned immediately.

And I'm asking myself if there is any reason not to use `encoding/json` in a separated **optional** method in order to make this check, normally after using `gjson.Parse(...)`.

`Result` could be the receiver for this method/function. I can think of two possibilities.

1) Just return a `bool` and do not explain what is wrong.

```
func (t Result) IsValidJson() bool {
	var jsonTester interface{}
	err := json.Unmarshal([]byte(t.Raw), &jsonTester)
	return err == nil
}
```

2) return an error explaining what is wrong, and the user must check against `== nil` for checking that the JSON is valid.

```
func (t Result) ValidateJson() error{
	var jsonTester interface{}
	return json.Unmarshal([]byte(t.Raw), &jsonTester)
}
```

Right now I'm doing this using additional helper methods in my project.

**Comment by tidwall** [comment]
Depending on the size of the JSON payload, the `json.Unmarshal` function can be a slow operation. 

If all you need to know is if the JSON is valid, then I recommend the `gjson.Valid(...)` function. It's super quick and performs no extra memory allocations.

For example:

```go
t := gjson.Get(json, "name")
if !gjson.Valid(t.Raw){
    // ... bad json
}
```

Though perhaps adding an additional function to Result is worth considering.

**Comment by martin-flaregames** [comment]
I feel dumb. I'm sorry, I missed that such a method was already in place. And IMO it makes little sense to add this method to `Result`. Thanks you.

**Comment by tidwall** [comment]
I don't have the method listed in the README, so it's totally understandable why it easy to miss. 
You're welcome. :)
