### ISSUE TITLE
@fromstr doesn't appear to work

### ISSUE THREAD

**Issue by lsh-0** [tidwall/gjson#356]
Using https://gjson.dev, an input of:

    name.last

yields

    "Anderson"

and I would expect using the modifier `@fromstr` like:

    name.last|@fromstr

to yield:

    Anderson

(without quotes), instead nothing is displayed.

Locally the `extracted_value.Exists()` is returning `false`.

Am I using `@fromstr` correctly? I've also tried `some.path.@fromstr` as well downgrading to `gjson@1.16.0` with the same results.

Thanks,

**Comment by tidwall** [comment]
The `@fromstr` modifier is used to unescape json that is stored in a string.

Using the path `person.@fromstr.last` with json
```
{"person":"{\"last\":\"Anderson\"}"}
```
returns `"Anderson"`.

**Comment by lsh-0** [comment]
ah ... so is there an equivalent to `jq  --raw-output` that would let me get at the string `Anderson` without quotes?

**Comment by tidwall** [comment]
```
gjson.Get("name.last").String()
```

**Comment by lsh-0** [comment]
Unfortunately the path is passed in by the user, much like https://gjson.dev

> @fromstr: Converts a string from json. Unwraps a json string.

It sounds like what I need but I was mistaken. Thanks for your time.

**Comment by tidwall** [comment]
No problem, glad you found a solution.
