### ISSUE TITLE
check the delimiter correctly

### ISSUE THREAD

**Issue by huangpeizhi** [tidwall/gjson#36]
Hi, tidwall:

I use the wrong JSON delimiter, and I can also get results without errors.

```
var gpsSample = `
{
    "id"&& "950446", 
    "lat": 23.1483333, 
    "lon": 113.2547222, 
    "height": 0, 
    "dir": 42.5, 
    "speed": 30, 
    "attr": "routecode::00540", 
    "group": "591a8e25d1779c525b732105", 
    "gpstime": "2017-05-23T11:31:24+08:00"
}
`

func TestGjson(t *testing.T) {
	require.Equal(t, "950446", gjson.Get(gpsSample, "id").String())
}
```

![image](https://user-images.githubusercontent.com/19602075/29394696-9675803c-833e-11e7-8f61-dee9ba4cff63.png)

**Comment by tidwall** [comment]
Hi huangpeizhi,

This is by design. GJSON does not return errors for invalid JSON. You'll need to check if the JSON is well formed prior to calling `gjson.Get()`. 

One option is to use the `gjson.Valid(json)` function.  

For example:

```go
if !gjson.Valid(json) {
    return errors.New("invalid json")
}
id := gjson.Get(json, "id").String()
name := gjson.Get(json, "name").String()
```

**Comment by huangpeizhi** [comment]
thanks!
