### ISSUE TITLE
Need help phrasing some json

### ISSUE THREAD

**Issue by insomnyawolf** [tidwall/gjson#37]
I have some json from Konachan ( )
I would like to get the values for the key1,key2,key3 or key 4 but i can only figure how to get the values for the first key like:

`
apiurl := " https://konachan.net/post.json?limit=4&tags=foxgirl"
	res, err := http.Get(apiurl)
	if err != nil {
		fmt.Println(err.Error())
	}
	defer res.Body.Close()
	thing, err := ioutil.ReadAll(res.Body)
	if err != nil {
		fmt.Println(err.Error())
	}
	cut1 := bytes.TrimPrefix(thing , []byte("["))
	cut2 := bytes.TrimSuffix(cut1  , []byte("]"))
        ans := gjson.ParseBytes(cut2)
        id := ans.Get("*id")
        fmt.Println(id)
`

My idea was geting the value of id in x key stored in a variable

**Comment by tidwall** [comment]
Hi @insomnyawolf,

You can get a specified array item by using it's index as the path, for example:
```go
item := gjson.GetBytes(thing, "0")
item
fmt.Println()
```

**Comment by tidwall** [comment]
Hi @insomnyawolf,

You can get a specified array item by using it's index as the path, for example:
```go
item := gjson.GetBytes(thing, "0")
println(item.String())
```

... will get the first item, and `gjson.GetBytes(thing, "1")` will get the second item.

Other examples:

```go
println(gjson.GetBytes(thing, "2.id").Int())
```
will print `248833`


```go
println(gjson.GetBytes(thing, "2.author").String())
```
will print `mattiasc02`

Does this help answer you question?

**Comment by insomnyawolf** [comment]
Thanks for the help.
Its exactly what i needed.
Thanks

**Comment by tidwall** [comment]
You're welcome. I'm closing this issue for now. Thanks for using GJSON!
