### ISSUE TITLE
Feature request: new method Position() on gjson.Result object

### ISSUE THREAD

**Issue by omani** [tidwall/gjson#41]
Hi,

somehow related to https://github.com/tidwall/sjson/issues/8.

it would be nice to have a method on the returning result object for getting the position where the object was found in the array if one uses:
```
field := gjson.GetBytes(jsonstring, `user.#[name="tidwall"]`)
```

and if jsonstring was an array of objects:
```
{
  "user": [
     {"id": ..., "name": "tidwall"},
     {"id": ..., "name": "omani"},
     {"id": ..., "name": "...."}
  ]
}
```

now I could get the position where the element was found with ```Pos()``` or ```Position()```:
```
fmt.Println(field.Pos())
// Output
0
```

are there any plans to implement this?

**Comment by tidwall** [comment]
Sorry for the delayed response. I agree that this would be very convenient in some cases, and something I'll consider in the future.

In the meantime perhaps a less convenient but still efficient workaround:

```go
var pos int
var field gjson.Result
gjson.Get(json, "user").ForEach(func(_, v gjson.Result) bool {
	if v.Get("name").String() == "tidwall" {
		field = v
		return false
	}
	pos++
	return true
})
if field.Exists() {
	fmt.Println(pos)
}
```

**Comment by omani** [comment]
yes. this is exactly how I've solved it. I am happy to hear this will be considered in the future.

thanks.

**Comment by tidwall** [comment]
I'm closing this issue for now, but adding the feature request as a potential future feature. Thanks
