### ISSUE TITLE
Errors are not using. Yes, it is a big problem.

### ISSUE THREAD

**Issue by XELAJ** [tidwall/gjson#42]
I don't understand, why are you hating errors? It is normal to return error that "sorry, i can't find this object in your json" when you call gjson.Get() or "sorry, i can't translate array to string, Cause... Cause it's an array" for result.String(). It is pretty easy, but you didn't made it, why?

**Comment by tidwall** [comment]
> I don't understand, why are you hating errors? It is normal to return error that "sorry, i can't find this object in your json" when you call gjson.Get() or "sorry, i can't translate array to string, Cause... Cause it's an array" for result.String(). It is pretty easy, but you didn't made it, why?

Perhaps GJSON isn't the best library for you.

**Comment by rbastic** [comment]
Politely handled. Myself and several coworkers love this library :) You're doing great work, keep it up!

**Comment by tidwall** [comment]
@rbastic thanks. :)
