### ISSUE TITLE
GetMany Result Value Missing

### ISSUE THREAD

**Issue by trujaytim** [tidwall/gjson#48]
Have found that if I have the following JSON to process:
{"bar": {"id": 99, "xyz": "my xyz"}, "foo": {"myfoo": [605]}}

And my expressions are:
"foo.myfoo", "bar.id", "bar.xyz", "bar.abc"

Then the GetMany result returns the following:
(blank - incorrect!)
99 (correct!)
my xyz (correct!)
(blank - correct!)

In this case the result for expression "foo.myfoo" should be the array [605] however the result is empty for this expression.

**Comment by tidwall** [comment]
Thanks for reporting. I just pushed an update that fixes this and #47.
