### ISSUE TITLE
Mysterious missing result!

### ISSUE THREAD

**Issue by donovanhide** [tidwall/gjson#54]
```
package main

import (
	"fmt"

	"github.com/tidwall/gjson"
)

func main() {

	json := `{"MarketName":null,"Nounce":6115}`
	r1 := gjson.GetMany(json, "Nounce", "Buys", "Sells", "Fills")
	fmt.Println(r1)
	r2 := gjson.GetMany(json, "Nounce", "Buys", "Sells")
	fmt.Println(r2)
	r3 := gjson.GetMany(json, "Nounce")
	fmt.Println(r3)
}
```
```
[   ]
[6115  ]
[6115]
```

This is a slightly bizarre bug, but I'd expect r1 to be equal to `[6115 ]`. Can't work out if it is related to the `null` in MarketName or the number of non-existent keys... Very mysterious :-)

**Comment by donovanhide** [comment]
Seems to be related to this code section:
https://github.com/tidwall/gjson/blob/master/gjson.go#L1881-L1885

**Comment by tidwall** [comment]
👍 Great find and thanks for isolating the issue. I added a bunch of tests to keep this problem from ever happening again.

**Comment by donovanhide** [comment]
Nice tests! Thanks for the rapid fix and a great package :-)
