### ISSUE TITLE
Strange behaviour in GetMany

### ISSUE THREAD

**Issue by dronnix** [tidwall/gjson#55]
Hi!
Flowing code: 
```go
json := `{"one": {"two": 2, "three": 3}, "four": 4, "five": 5}`
results := gjson.GetMany(json, "four", "five", "one.two", "one.six")
for i,r := range  results {
	fmt.Printf("%d: %v\n", i, r)
}
```
produces:

> 0: 
1: 
2: 2
3:
 
Is it correct?  
Thank You!

**Comment by tidwall** [comment]
That's not correct. I'll need to dig around a little and see what the heck is going on. 
Thanks for reporting!

**Comment by tidwall** [comment]
I just pushed an update that should addresses the issue.
