### ISSUE TITLE
Unable to access the index of array when apply ForEach func

### ISSUE THREAD

**Issue by jinxjinxagain** [tidwall/gjson#56]
I have read the code and comment on `func ForEach`,
you didn't pass the index to arguments on purpose,
thus, if I want to get the index of each item, i need to do like this
```golang
var p = res.Array()
for i := 0; i < len(p); i++ {
}
```
And I also program with javascript, you know, javascript has the prototype foreach too.
refs: [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach)
So, when the first time I see this function, I may think the key will be the index of items in array.
what's your recommend for getting index about this?

**Comment by tidwall** [comment]
This is the pattern that I use:

```go
var index int
res.ForEach(func(_, v gjson.Result) bool {
        println(index, v.String())
	index++
	return true
})
```

**Comment by jinxjinxagain** [comment]
Yeah, it is a nice solution for that.
but may this will be better?
```golang
res.ForEach(func(key, value gjson.Result) bool {
    println(key.Int(), value.String())
    return true
})
```
whatever, personal opinion

**Comment by tidwall** [comment]
Thanks for the suggestion.

I agree that assigning the key as the index is a better solution. I'll consider it but I need to evaluate the pitfalls first. I think it would be a breaking change for some people, as the key is occasionally compared with `gjson.Null` to determine parent type. 

Such as, https://github.com/minio/minio/blob/e3d841ffd17e96a69b0db889cb7d81864ebef61e/cmd/config-current.go#L253

**Comment by jinxjinxagain** [comment]
Yeah, it seems the best way to distinguish between array and object...
Anyway, thx for response...

**Comment by tidwall** [comment]
You're welcome.
