### ISSUE TITLE
Possible gjson parsing bug?

### ISSUE THREAD

**Issue by rbastic2** [tidwall/gjson#59]
Hi,

Wanted to say firstly thanks for all the hard work on gjson. I love this library. Unfortunately, I might've found another bug to report? I just tested this against the latest release.

Please see this repo: https://github.com/rbastic2/gjson-bug

Running go test -v should cause the test to fail. The data used is in rules_test.go  (see the  getHookRules() function)  and the problematic path is in the error:

HOOKFUNCTIONS.SetUpdate.#0.is_true

I have a workaround for this bug in the meantime, by not retrieving the entire path on every instance (wasteful, anyway). However, I thought it would present a good opportunity to further fuzz gjson for you.  Hope I'm not doing something wrong with the path syntax :D 

Thanks in advance!

**Comment by tidwall** [comment]
Hi again. I haven’t tested your example yet, but upon a cursory look, the problem may be with the `#` symbol in your path. When accessing array values by index you only need the number like such:

```
HOOKFUNCTIONS.SetUpdate.0.is_true
```

Perhaps this might fix the problem from you side. If not then let me know and I’ll investigate further.

**Comment by rbastic2** [comment]
Thanks again, silly error on my part.

**Comment by tidwall** [comment]
You’re welcome. :)
