### ISSUE TITLE
Support JSON lines

### ISSUE THREAD

**Issue by acka47** [tidwall/gjson#60]
I want to use [jj](https://github.com/tidwall/jj) to parse large JSON lines (http://jsonlines.org/) files. It looks like this isn't supported yet. Would be great if you could add JSON lines support. (JQ also has it.)

**Comment by tidwall** [comment]
This is something I've been wanting too. I plan on getting it done soon. Thanks!

**Comment by tidwall** [comment]
I just pushed and update to GJSON and JJ that now support JSON Lines using the `..` prefix.

**Comment by acka47** [comment]
Thanks!
