### ISSUE TITLE
Unmarshal deprecation

### ISSUE THREAD

**Issue by MatthewHartstonge** [tidwall/gjson#63]
Hi there,

I've just been looking at you lib and noticed since `v1.0.2` Unmarshal is marked as deprecated. Just wondering why?
And if so, would you be happy for me to splice out the unmarshal code to my own private project to wrap gson if truly deprecating `gson.Unmarshal` in future.

I've got a situation where I've got a third party API that has a poor JSON encoder, where if a string happens to be a number, it becomes a JSON number, while the API is documented as being a string attribute. (For example.. a key called `Username` ... )

While starting to mash out a mush of structs, Unmarshaller interfaces and binding a silly toString reflect func for every field, I had a look around and came across GJSON. The code you have converts as per the struct specification, which is perfect for this use case.. `json/encoder.Unmarshal` breaks when it comes across numbers.

```
panic: json: cannot unmarshal number into Go struct field username of type string
```

Or is there a better-er solution? (I will be version pinning..)

**Comment by tidwall** [comment]
Hi,

> I've just been looking at you lib and noticed since v1.0.2 Unmarshal is marked as deprecated. Just wondering why?

I felt that the function was confusing to people in the Go community. The difference between the stdlib Unmarshal and gjson Unmarshal was a bit too broad, and I found myself fielding more questions than I cared to spend time on.

It's still a pretty good function though. Especially with number handling and type detection.

I won't be removing the function from the package until 2.0. But moving forward you can fork the project, or use the `v1.0.2` tag, or just copy the code into your project if you like (as long as you include the LICENSE notice).

**Comment by MatthewHartstonge** [comment]
Awesome!

Ironically, It feels like the stdlib encoder _should_ attempt to do what your Unmarshal does, or at least be a configurable encoder option depending on the potential performance hit... :)

As for your suggestions, will do!
Thank you! GSON is fantastic! 👌

**Comment by tidwall** [comment]
Thanks for the kind words :)
