### ISSUE TITLE
Help writing complex queries

### ISSUE THREAD

**Issue by slaterx** [tidwall/gjson#64]
Hi @tidwall!

I'm struggling to write some more complex queries using gjson. Using your json example in http://tidwall.com/gjson-play/:

```json
{
  "name": {"first": "Tom", "last": "Anderson"},
  "age":37,
  "children": ["Sara","Alex","Jack"],
  "fav.movie": "Deer Hunter",
  "friends": [
    {"first": "Dale", "last": "Murphy", "age": 44},
    {"first": "Roger", "last": "Craig", "age": 68},
    {"first": "Jane", "last": "Murphy", "age": 47}
  ]
}
```

How can I write a query to get the friends.#.age when last is Murphy and first is Dale? I tried something like `friends.#[last=="Murphy" && first=="Dale"]#.age` without success. 

Also, how can I write a query to get same field when last name is Murphy or Craig? I tried something like `friends.#[last=="Murphy" || last=="Craig"]#.age` without success either. 

I'm writing in the hopes I could get some light on how to do it or, in the case it's not supported, to update the documentation accordingly.

Thanks,
Gleidson

**Comment by tidwall** [comment]
Hi Gleidson,

The `&&` and `||` are not currently available and gjson is limited to a single query per path. 

At some point I may add this ability, but until then I recommend using a `ForEach` loop:

```go
var res gjson.Result
gjson.Get(json, "friends").ForEach(
	func(_, v gjson.Result) bool {
		if v.Get("last").String() == "Murphy" && v.Get("last").String() == "Murphy" {
			res = v
			return false
		}
		return true
	},
)
if res.Exists() {
	fmt.Println(res.String())
}
```

**Comment by nkev** [comment]
This is a very useful example Josh! Recommend putting it in the readme. I think you may have intended to check `first` and `last` though. 

While I have you, is  `ForEach` the fastest way to unmarshal to struct with gjson? I'd love to see it in the benchmarks.

**Comment by dsgthb** [comment]
Hi @tidwall,
How can I write a query to get a JSON object array's field value where one element of the nested child JSON object array match a condition? (i.e. something like ``` friends.hobbies#[%"eat"]#.last```)


```golang
package main

import "github.com/tidwall/gjson"

const json = `{
  "name": {"first": "Tom", "last": "Anderson"},
  "age":37,
  "children": ["Sara","Alex","Jack"],
  "fav.movie": "Deer Hunter",
  "friends": [
    {"first": "Dale", "last": "Murphy", "age": 34, "hobbies" : [ "sleeping", "eat" ] },
    {"first": "Roger", "last": "Craig", "age": 68, "hobbies" : [ "sailing", "horses", "gardening" ] },
    {"first": "Jane", "last": "Murphy", "age": 47, "hobbies" : [ "cycling" ] }
  ]
}`

func main() {
	value := gjson.Get(json, `friends.#[first%"D*"].hobbies`)
	println(value.String())
}
```

Querying the whole child nested JSON object array it's straightforward where an element of the parent JSON object array match a condition.

I'm writing to better understand and to know if a matching condition on a child nested JSON object array it's a supported feature.

Thanks in advance.

**Comment by tidwall** [comment]
@nkev 

> Is ForEach the fastest way to unmarshal to struct with gjson?

The ForEach is pretty fast. When called most child objects are parsed using the optimized [parseSquash](https://github.com/tidwall/gjson/blob/master/gjson.go#L863-L909) operation.

**Comment by tidwall** [comment]
@dsgthb Sorry for the delayed response. 

If I understand correctly you are looking to possibly return a parent object by matching on a child. I think that this is a form of backtracking, which unfortunately is not currently supported.

**Comment by dsgthb** [comment]
Hi @tidwall,
no worries and thank you for the reply. Exactly, you've hit the target. However, using "encoding/json" package (and some line of ugly code...) I'm able to fetch a parent object by matching on a child value, I guess  ;-)
```golang
package main

import (
	"fmt"
	"log"
	"encoding/json"
	"github.com/tidwall/gjson"	
)

const sjson = `{
  "name": {"first": "Tom", "last": "Anderson"},
  "age":37,
  "children": ["Sara","Alex","Jack"],
  "fav.movie": "Deer Hunter",
  "friends": [
    {"first": "Dale", "last": "Murphy", "age": 34, "hobbies" : [ "sleeping", "eat", "fishing" ] },
    {"first": "Roger", "last": "Craig", "age": 68, "hobbies" : [ "sailing", "horses", "gardening", "eat" ] },
    {"first": "Jane", "last": "Murphy", "age": 47, "hobbies" : [ "cycling" ] }
  ]}`

type person struct {
	Name struct {
		First string `json:"first"`
		Last  string `json:"last"`
	} `json:"name"`
	Age      int      `json:"age"`
	Children []string `json:"children"`
	Favmovie string   `json:"fav.movie"`
	Friends  []struct {
		First   string   `json:"first"`
		Last    string   `json:"last"`
		Age     int      `json:"age"`
		Hobbies []string `json:"hobbies"`
	} `json:"friends"`
}

func main() {

	value := gjson.Get(sjson, `friends.#[first%"D*"].hobbies`)
	s := value.Array()
	println("value.String():", value.String(),"\n")
	for k, v := range s {
		println("try:", k)
		if v.String() == "eat" {
			println("  =>", v.String())
		}
	}
	
	
	
	println("\nNow try to print the friend's lastname who like to eat using encoding/json package (and some line of ugly code)")
	
	var someone person
	bjson := []byte(sjson)

	if err := json.Unmarshal(bjson, &someone); err != nil {
		log.Println(err)
	}

	var lastname string = "Initial value"
	for _, dude := range someone.Friends {
		for _, attitude := range dude.Hobbies {
			if attitude == "eat" {
				lastname = dude.Last
				fmt.Printf("Lastname: %s\n", lastname)
				break
			}
		}
	}
}
```

**Comment by tidwall** [comment]
@dsgthb 

Also using the `ForEach` you can do a similar operation:

```go
package main

import (
	"fmt"

	"github.com/tidwall/gjson"
)

const sjson = `{
  "name": {"first": "Tom", "last": "Anderson"},
  "age":37,
  "children": ["Sara","Alex","Jack"],
  "fav.movie": "Deer Hunter",
  "friends": [
    {"first": "Dale", "last": "Murphy", "age": 34, "hobbies" : [ "sleeping", "eat", "fishing" ] },
    {"first": "Roger", "last": "Craig", "age": 68, "hobbies" : [ "sailing", "horses", "gardening", "eat" ] },
    {"first": "Jane", "last": "Murphy", "age": 47, "hobbies" : [ "cycling" ] }
  ]}`

func main() {
	var friendsThatEat []gjson.Result
	gjson.Get(sjson, "friends").ForEach(func(_, friend gjson.Result) bool {
		friend.Get("hobbies").ForEach(func(_, hobby gjson.Result) bool {
			if hobby.String() == "eat" {
				friendsThatEat = append(friendsThatEat, friend)
				return false
			}
			return true
		})
		return true
	})
	for _, friend := range friendsThatEat {
		fmt.Printf("%v\n", friend.Get("first"))
	}
}
```

**Comment by dsgthb** [comment]
@tidwall 
Your solution using ```ForEach``` looks great! Smooth and elegant. Thanks so much.  ;-)

**Comment by tidwall** [comment]
I'm closing this issue for now but feel free to reopen if you have further questions.

Thanks!

**Comment by litao09h** [comment]
The && and || are not available now at 2023-03
I intend to save the expression as data configuration, so that the code does not need to be changed when modifying

**Comment by volans-** [comment]
[fast-forward ~5 years]

### From: @dsgthb 
> How can I write a query to get a JSON object array's field value where one element of the nested child JSON object array match a condition? (i.e. something like ` friends.hobbies#[%"eat"]#.last`)

As also explained in #315 it's now possible to get siblings values doing nested queries. So with your example input with query:
```
friends.#(hobbies.#(%"eat")#|0)#.last
```

you get:
```json
["Murphy"]
```

The `|0` here is needed because `#(...)#` queries return empty array for non-matching elements hence we want to exclude them. See the [dot-vs-pipe](https://github.com/tidwall/gjson/blob/master/SYNTAX.md#dot-vs-pipe) docs.

### From: @slaterx (cc @litao09h )

Piping multiple queries is possible to do the `&&` behaviour. So for example with query:
```
friends.#(last=="Murphy")#|#(first=="Dale")#.age
```
you get:
```json
[44]
```

While using [multipaths](https://github.com/tidwall/gjson/blob/master/SYNTAX.md#multipaths) it's possible to do the `||` behaviour, so with query:
```
friends.[#(last=="Murphy")#,#(last=="Craig")#].@flatten.#.age
```
you get:
```json
[44,47,68]
```
The `@flatten` is to flat the nested arrays and make disappear the empty array of a possible multipaths that doesn't match any item.
