### ISSUE TITLE
Struct tags to help marshall directly into struct objects

### ISSUE THREAD

**Issue by arriqaaq** [tidwall/gjson#72]
Hey @tidwall 

I think it would be great if we could have struct tags which will help unmarshall the string directly into a given struct.

type A struct {
      B string `gjson:"data.id"`
}

Lemme know your thoughts on it

**Comment by tidwall** [comment]
Hi @arriqaaq 

Could you provide an little example on how you would use this? I'm trying to better understand how the code for interfacing with these tags might work.

**Comment by arriqaaq** [comment]
Hey @tidwall ,

I was thinking something similar along these lines

https://gist.github.com/arriqaaq/aefc61daddaa5a8509120e27d2a76880

**Comment by tidwall** [comment]
I like this approach actually.

**Comment by tidwall** [comment]
Thanks again for the suggestion, but I've decided to shelve this idea for now. It's just too big of a feature and would require an investment in time that I don't have right now.

Thus I'm closing this issue for now, but I may reopen it in the future.

**Comment by arriqaaq** [comment]
@tidwall Thanks for looking into it, appreciate it. I shall try to work on it, may be in future if you could accept the PR or work it out in a better way yourself.

**Comment by tidwall** [comment]
Sounds good. Let me know if you need any feedback along the way.
