### ISSUE TITLE
Validation skips characters after object key until quote is found

### ISSUE THREAD

**Issue by twmb** [tidwall/gjson#73]
For `TestValidBasic`:

```diff
+       testvalid(`{"a":"b",2"1":2}`, false)
```

this specific issue is right here:
https://github.com/tidwall/gjson/blob/3cd3a1192327ac5e24f7e87824be578b0b07c604/gjson.go#L1868-L1869

**Comment by tidwall** [comment]
thanks for reporting this issue!
