### ISSUE TITLE
Get().String() converts integer to float

### ISSUE THREAD

**Issue by dfranklandgdl** [tidwall/gjson#74]
With input of an int64 value larger than 2^53, represented as a number in JSON (no quotes), the output of `result.Int()` is correct but `result.String()` is not, as it's stored as a float causing loss of precision. This code reproduces the issue: 
  
 ```
	i := 9007199254740993                 //2^53 + 1
	j := fmt.Sprintf(`{"data":%d}`, i)    //No quotes around value!! 
	res := gjson.Get(j, "data")
	fmt.Println("string:", res.String(), "int:", res.Int())

	//Output: 
	//string: 9007199254740992 int: 9007199254740993
```
Not sure if this is known behavior, but it seems that the result should be the same representation for String() and Int(). 

This is on a 64bit OS, of course :) 

Thanks!

**Comment by tidwall** [comment]
Thanks for reporint. I agree and made a change where `String()` maintains the original JSON value for large signed/unsigned integers.
