### ISSUE TITLE
gjson.ValidBytes() question

### ISSUE THREAD

**Issue by pathbox** [tidwall/gjson#76]
Hi,
  I use gjson in my project. I have a question about `isJson := gjson.ValidBytes(b)`.
  When b is `333`, `isJson` value is true, is it right? As we konw,  `333` is not json data struct, is it?

**Comment by tidwall** [comment]
Hi,  
`333` is a valid json number and `gjson.ValidBytes()` recognizes all json types: number, boolean, null, array, and object. This works the same way as the `json.Valid() function of the `enocding\json` package.

If you want to also detect if the json is an object then you can combine both `ValidBytes` with `ParseBytes`. 

```go
isValidObject := gjson.ValidBytes(b) && gjson.ParseBytes(b).IsObject()
```

**Comment by pathbox** [comment]
Get it, thank you so much, I will try it.

**Comment by tidwall** [comment]
I hope this solution worked out for you. I'm closing this issue for now, but if you run into any problems feel free to reopen. Thanks!
