### ISSUE TITLE
How to Iterate first level array json?

### ISSUE THREAD

**Issue by digiaditya** [tidwall/gjson#90]
`package main

import "github.com/tidwall/gjson"

const json = `[ "Ford", "BMW", "Fiat" ]`

func main() {
result := gjson.Get(json, "*")
result.ForEach(func(key, value gjson.Result) bool {
  println(value.String()) 
  return true // keep iterating
})
}`

**Comment by tidwall** [comment]
The `Parse` function is what you are looking for:

```
package main

import "github.com/tidwall/gjson"

const json = `[ "Ford", "BMW", "Fiat" ]`

func main() {
	result := gjson.Parse(json)
	result.ForEach(func(key, value gjson.Result) bool {
		println(value.String())
		return true // keep iterating
	})
}
```

**Comment by tidwall** [comment]
I'm closing this issue for now, but feel free to reopen if needed.
