### ISSUE TITLE
Nested array value + Exists() == inconsistent results ?

### ISSUE THREAD

**Issue by ImreSamu** [tidwall/gjson#91]
Thank you for this tool!  :heart: 

I have found a strange use case : 

Example code:
```go
	json := `{
				"programmers": [
					{
						"firstName": "Janet", 
						"lastName": "McLaughlin", 
					}, {
						"firstName": "Elliotte", 
						"lastName": "Hunter", 
					}, {
						"firstName": "Jason", 
						"lastName": "Harold", 
					}
				]
			}
	  `
	testcases := [...]string{
		"programmers.#.age",
		"programmers.#.lastName",
		"managers.#.lastName",
	}

	for _, test := range testcases {
		fmt.Println(test,
			"  Exists()=", gjson.Get(json, test).Exists(),
			"  Get()=", gjson.Get(json, test))
	}
```

output:

```
programmers.#.age   Exists()= true   Get()= []
programmers.#.lastName   Exists()= true   Get()= ["McLaughlin","Hunter","Harold"]
managers.#.lastName   Exists()= false   Get()=
```

expecting:  
*  `gjson.Get(json, "programmers.#.age").Exists()`  ==> **false**

now:    
* `gjson.Get(json, "programmers.#.age").Exists()`  ==> **true**

It is strange for me,  I don't know it is a bug or an undocumented feature

**Comment by tidwall** [comment]
Though a little strange, this is expected behavior. 

The `programers.#` will return an array type if the `"programers"` key exists an array. If there are no matching objects in the json array, then the are result array will be just an empty `[]`. 

But because the `"managers"` key does not exist, the non-existent result is returned.

**Comment by ImreSamu** [comment]
Thanks for the answer! :heart:

> Though a little strange, this is expected behavior. 

My real word use case
* fast filtering wikidata json values with: `"claims.P17.#.qualifiers.P1310"` , 
and just checking the value Exist or not. ( sometimes no `.P17`, sometimes no `.qualifiers` or `.qualifiers.P1310` )  .  



**My workaround:** - calling  ` (len(gjson.Get(json, test).Array()) > 0) ` instead of .Exists()


```golang
	testcases := [...]string{
		"programmers.#.age",
		"programmers.#.lastName",
		"managers.#.lastName",
	}

	for _, test := range testcases {
		fmt.Println(test,
			"\tExistsArray()=", (len(gjson.Get(json, test).Array()) > 0),
			"\tExists()=", gjson.Get(json, test).Exists(),
			" \tGet()=", gjson.Get(json, test))
	}
```	
	
output:	
```	
programmers.#.age       ExistsArray()= false    Exists()= true      Get()= []
programmers.#.lastName  ExistsArray()= true     Exists()= true      Get()= ["McLaughlin","Hunter","Harold"]
managers.#.lastName     ExistsArray()= false    Exists()= false     Get()=
```


> If there are no matching objects in the json array, then the are result array will be just an empty [].

(according the README) _"The result.Array() function returns back an array of values. If the result represents a **non-existent value, then an empty array will be returned**."_

imho: maybe need an extra documentation, that the reverse is not true
*  "[] empty array" -->   NOT a **non-existent value** according to the   [` .Exists()`](https://godoc.org/github.com/tidwall/gjson#Result.Exists)  function 


### And thanks again !
:heart: :heart: :heart:
