### ISSUE TITLE
Array Value

### ISSUE THREAD

**Issue by gmonk** [tidwall/gjson#92]
I've looked at the docs and I'm not seeing any way to query a single value from below.  I would like to pull value 5 which is an int from from group1 but I have tried every possible query on that array i can think of to no avail.  Is this possible or do I need to iterate over the values

"detectors": {
		"group1": [3, 4, 5, 7],
		"group2": [19, 20, 21, 23],
		"group3": [26, 27, 28],
		"group4": [34, 35, 36, 37, 39],
		"group5": [42, 43, 44]
	}

**Comment by tidwall** [comment]
You'll need to iterate over the numbers using something like the `ForEach` function. 
The current query language is limited to only finding objects based on child values.
