### ISSUE TITLE
How to read all matches from json object?

### ISSUE THREAD

**Issue by poornalingam** [tidwall/gjson#94]
Thanks for the great work!!

My goal is to read all `get` method `descriptions` from below json (example:1).  `paths.*.get.description` return single(first) object and ignore the remaining matches.`paths.#.get.description` works well if its declared as array of objects (refer example:2). 

Is there a way to get all `get.descriptions` from object collection (example:1)?  

Example: 1
```
{
  "paths": {
    "/": {
      "get": {
        "description": "Get cars in the collection"
      },
      "post": {
        "description": "Creates a new car in the collection"
      }
    },
    "/owners": {
      "get": {
        "description": "Gets a collection of owners from the server."
      },
      "post": {
        "description": "Creates a new owner in the collection"
      }
    }
  }
}
```
Query: `paths.*.get.description`
output:
`Get cars in the collection`
My expectation is:
`["Get cars in the collection","Gets a collection of owners from the server."]`

-----

Example:2
```
{
  "paths": [
    "/": {
        "get": {
            "description": "Get cars in the collection"
        },
        "post": {
            "description": "Creates a new car in the collection"
        }
      },
      "/owners": {
          "get": {
              "description": "Gets a collection of owners from the server."
          },
          "post": {
              "description": "Creates a new owner in the collection"
          }
      }
  ]
}
```
Query: `paths.#.get.description`
output:
`["Get cars in the collection","Gets a collection of owners from the server."]`

**Comment by poornalingam** [comment]
Thanks for the response and alternative approach!!

Is there a design constraint to read all the object elements using `#`  or `*` operator for object too?

**Comment by tidwall** [comment]
Unfortunately, the # is designed to only work on an array, and the * are designed to be a very simple operation that only matches on the first key.

I'm closing this issue for now, but feel free to reopen if you have further questions.
