### ISSUE TITLE
How can I get value from JSON that haven't got "key" (just random string)

### ISSUE THREAD

**Issue by anhhtz** [tidwall/gjson#96]
Hi,

Hope you can help me to resolve the problem below:

```json
{
  "some key": "value",
  "another key": "another value",
  "users": {
    "john": [
      {
        "department": 1,
        "age": 20,
        "job": "something job"
      }
    ],
    "david": [
      {
        "department": 2,
        "age": 30,
        "job": "example job"
      }
    ],
    "marry": [
      {
        "department": 9,
        "age": 40,
        "job": "another job"
      }
    ]
  }
}
```

I cannot find any solution (`Marshal, Unmarshal, map[string]interface{}`) to parse the `users` segment.

I hope you can give me some ideas, please.

Thanks in advanced !

**Comment by xlanor** [comment]
My answer may be wrong, because I just picked up golang this morning and used this library, but cant you use the .Map() function?
``` go
// assuming the JSON string is stored in a variable js
users := gjson.Get(body,"users")
userMap := users.Map() // converts from a Result into a Map
for user, detailsArr := range userMap{
        ...
}

```
Apologies if this doesn't help. I'm new to golang (and this library myself)

**Comment by anhhtz** [comment]
Thanks @xlanor so much !

I tried parse the json with pure Go and it 's work perfect !

Thanks so much about your helping. You are awesome !
