### ISSUE TITLE
Array as query parameter

### ISSUE THREAD

**Issue by ndlarsen** [tidwall/gjson#99]
Is there any way to supply an array as query parameter and query the json for all elements in the array rather than traversing the data multiple times?

If I have this json data:

`jsonData = {
    "id": 1,
    "name": "Leanne Graham",
    "username": "Bret",
    "email": "Sincere@april.biz",
    "address": {
    "street": "Kulas Light",
    "suite": "Apt. 556",
    "city": "Gwenborough",
    "zipcode": "92998-3874",
    "geo": {
        "lat": "-37.3159",
        "lng": "81.1496"
        }
    },
    "phone": "1-770-736-8031 x56442",
    "website": "hildegard.org",
    "company": {
        "name": "Romaguera-Crona",
        "catchPhrase": "Multi-layered client-server neural-net",
        "bs": "harness real-time e-markets"
    }
}`

and this array

`var arr = []string{
    "address.street",
    "address.geo.lat"
}`

then a funtion such as gjson.Get(jsonData, arr)?

Thanks

**Comment by tidwall** [comment]
Yes. with `gjson.GetMany(jsonData, arr...)`. Which will return an array with the same number of results as inputs.

**Comment by tidwall** [comment]
I'm closing this issue, but feel free to reopen if you have further questions.
